### ISSUE TITLE
Two-way conversion between Range and String (e.g. aids GSON)

### ISSUE THREAD

**Issue by dimo414** [google/guava#1911]
Ranges have nice, readable toStrings(), like:

```
Range.closed(1,10).toString();
```

> ```
> [1‥10]
> ```

But if you try to serialize a Range using [Gson](https://code.google.com/p/google-gson/) you get something much more unpleasant:

```
new Gson().toJson(Range.closed(1, 10));
```

> ```
> {
>   "lowerBound": {
>     "endpoint": 1
>   },
>   "upperBound": {
>     "endpoint": 10
>   }
> }
> ```

And, even better, this structure is not deserializable:

```
gson.fromJson(gson.toJson(Range.closed(1, 10), Range.class);
```

> ```
> java.lang.RuntimeException: Unable to invoke no-args constructor for com.google.common.collect.Cut<C>. Register an InstanceCreator with Gson for this type may fix this problem.
>   at com.google.gson.internal.ConstructorConstructor$12.construct(ConstructorConstructor.java:210)
>   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:162)
>   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
>   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
>   at com.google.gson.Gson.fromJson(Gson.java:803)
>   at com.google.gson.Gson.fromJson(Gson.java:768)
>   at com.google.gson.Gson.fromJson(Gson.java:717)
>   at com.google.gson.Gson.fromJson(Gson.java:689)
>   ... 33 elided
> Caused by: java.lang.reflect.InvocationTargetException: java.lang.InstantiationException: com.google.common.collect.Cut
> ......
> Caused by: java.lang.InstantiationException: com.google.common.collect.Cut
> ......
> ```

I've personally worked around this problem by defining my own Range/String converters which outputs and can parse strings like Range's existing toString() method:

```
/**
 * Converter between Range instances and Strings, essentially a custom serializer for more
 * human-readable Ranges. This is particularly useful because Gson does not handle Ranges well.
 */
public static <T extends Comparable<? super T>>
    Converter<Range<T>, String> rangeConverter(Converter<T, String> elementConverter)

/**
 * Converter between RangeSet instances and Strings, essentially a custom serializer for more
 * human-readable RangeSets. This is particularly useful because Gson does not handle RangeSets well.
 */
public static <T extends Comparable<? super T>>
    Converter<RangeSet<T>, String> rangeSetConverter(Converter<T, String> elementConverter)
```

@kevinb9n notes:

> If we want to explore this idea, we should probably first explore doing it for plain old Collections. What delimiting/escaping logic is the best default, and would users be content with that, or just want the ability to configure it?

**Comment by swankjesse** [comment]
I'm hoping to make this a lot easier in Moshi, and perhaps Gson too if I can convince the other maintainers!
https://github.com/square/moshi/issues/29

Approximately how it'd work is Range would implement these two private methods:

```
  private Object toJson() {
    return Arrays.asList(
        lowerType == BoundType.OPEN ? "(" : "[",
        lowerBound,
        upperBound,
        upperType == BoundType.OPEN ? ")" : "]");
  }
  private static Object fromJson(Object json) {
    List list = (List) json;
    if (list.size() != 4) throw new IllegalArgumentException();
    BoundType lowerType = list.get(0).equals("(") ? BoundType.OPEN : BoundType.CLOSED;
    Object lower = list.get(1);
    Object upper = list.get(2);
    BoundType upperType = list.get(3).equals(")") ? BoundType.OPEN : BoundType.CLOSED;
    return new Range(lowerType, lower, upper, upperType);
  }
```
Then automagically the JSON form would be something like this:
```
[ "(", 5, 10, "]" ]
```

**Comment by bjmi** [comment]
A `Range.parse(Charsequence)` method would be very useful for all cases where conversion comes into play.
E.g. spring conversion service could convert ranges from string that are defined as in-place definitions in spring xml and inject them as "real" objects.

**Comment by dimo414** [comment]
Sorry, I don't have cycles to implement this at the moment, though I do think it's a good idea.

**Comment by pedro93** [comment]
Hello, 

I've just come across this limitation at work. Using @swankjesse's proposed solution worked for me.
Would the maintainers be ok with a PR that add the appropriate parsing method to the Range class?
Something in the lines of:

```java
public final class Range<C extends Comparable> implements Predicate<C>, Serializable {
    
   public static Range<C> parse(final String string) {
        final BoundType lowerType = string.charAt(0) == '(' ? BoundType.OPEN : BoundType.CLOSED;
        final int i = string.indexOf('‥');
        // These 2 casts may not work, in which case passing a fromString lambda as a parameter for the C type could work.
        final C lower = (C) string.substring(1, i);
        final C upper = (C) string.substring(i+1, string.length()-1);
        final BoundType upperType = string.charAt(string.length() -1) == ')' ? BoundType.OPEN : BoundType.CLOSED;
        return Range.range(lower, lowerType, upper, upperType);
    }
}
```

This method would parse the output of `Range.toString()`

**Comment by neewrobert** [comment]
I was facing the same issue. needing to serialise/deserialise Ranges in REST APIs and properties file with readable JSON instead of verbose object notation.                                                                                                                    
                                                                                                                                                                                                                                                               
  While waiting for a native solution, I created a small library that handles this: [guava-range-parser](https://github.com/neewrobert/guava-range-parser)                                                                                                     
                                                                                                                                                                                                                                                               
  It parses strings like `"[0..100)"` back into `Range.closedOpen(0, 100)` and includes a Jackson module for automatic JSON serialization.                                                                                                                     
                                                                                                                                                                                                                                                               
  ```java                                                                                                                                                                                                                                                      
  Range<Integer> range = RangeParser.parse("[0..100)", Integer.class);                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
  Hope it helps someone with the same problem!
