### ISSUE TITLE
Build Failed on Guava Repository

### ISSUE THREAD

**Issue by confile** [google/guava#1940]
After trying: ``mvn clean install ``  on the Guava repo I get the following errors:

```
Jan 10, 2015 1:24:49 AM com.google.common.util.concurrent.ServiceManager <init>
WARNUNG: ServiceManager configured with no services.  Is your application configured properly?
com.google.common.util.concurrent.ServiceManager$EmptyServiceManagerWarning
	at com.google.common.util.concurrent.ServiceManager.<init>(ServiceManager.java:194)
	at com.google.common.util.concurrent.ServiceManagerTest.testEmptyServiceManager(ServiceManagerTest.java:346)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:35)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:115)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)

Jan 10, 2015 1:24:49 AM com.google.common.util.concurrent.ServiceManager$ServiceListener failed
SCHWERWIEGEND: Service  [FAILED] ha

Running com.google.common.util.concurrent.UncaughtExceptionHandlersTest
Jan 10, 2015 1:24:53 AM com.google.common.util.concurrent.UncaughtExceptionHandlers$Exiter uncaughtException
SCHWERWIEGEND: Caught an exception in Thread[Thread-779,5,main].  Shutting down.
java.lang.Exception
	at com.google.common.util.concurrent.UncaughtExceptionHandlersTest.testExiter(UncaughtExceptionHandlersTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec
	at java.lang.reflect.Method.invoke(Method.java:606)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:35)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:115)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)

Running com.google.common.util.concurrent.UninterruptibleMonitorTest
Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.378 sec
Running com.google.common.util.concurrent.WrappingExecutorServiceTest
...
Tests run: 597008, Failures: 16, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Guava Maven Parent ................................ SUCCESS [0.256s]
[INFO] Guava: Google Core Libraries for Java ............. SUCCESS [16.834s]
[INFO] Guava Testing Library ............................. SUCCESS [25.873s]
[INFO] Guava Unit Tests .................................. FAILURE [5:36.508s]
[INFO] Guava GWT compatible libs ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6:20.103s
[INFO] Finished at: Sat Jan 10 01:24:53 CET 2015
[INFO] Final Memory: 47M/549M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.7.2:test (default-test) on project guava-tests: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/mg/Downloads/GWT/guava/guava-tests/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :guava-tests

```

**Comment by cpovirk** [comment]
Can you find the section of the log that shows which tests failed? I see "Failures: 16" in the final summary, but can you see which "Running com.google.common.SomeTest" section those failures come from? While I see the logging from UncaughtExceptionHandlersTest and probably ServiceManagerTest, that logging is expected. (It would be nice for us to silence it, but we haven't.)

My initial suspicion from seeing "SCHWERWIEGEND" in your output is that you're seeing bug 1567, which we really ought to fix.

**Comment by confile** [comment]
Here it is: 

```
Running com.google.common.base.StopwatchTest
Tests run: 20, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.011 sec <<< FAILURE!
```
Note that I compile with Java8.

**Comment by confile** [comment]
```
Failed tests: 
  testToString(com.google.common.base.StopwatchTest): null expected:<0[.]000 ns> but was:<0[,]000 ns>
  testSimple(com.google.common.util.concurrent.RateLimiterTest): null expected:<[R0[.00, R0.20, R0.]20]> but was:<[R0[,00, R0,20, R0,]20]>
  testSimpleWithWait(com.google.common.util.concurrent.RateLimiterTest): null expected:<[R0[.00, U0.20, R0.00, R0.]20]> but was:<[R0[,00, U0,20, R0,00, R0,]20]>
  testSimpleAcquireReturnValues(com.google.common.util.concurrent.RateLimiterTest): null expected:<[R0[.00, U0.20, R0.00, R0.]20]> but was:<[R0[,00, U0,20, R0,00, R0,]20]>
  testOneSecondBurst(com.google.common.util.concurrent.RateLimiterTest): null expected:<[U1[.00, U1.00, R0.00, R0.00, R0.00, R0.00, R0.]20]> but was:<[U1[,00, U1,00, R0,00, R0,00, R0,00, R0,00, R0,]20]>
  testWarmUp(com.google.common.util.concurrent.RateLimiterTest): null expected:<[R0[.00, R1.38, R1.13, R0.88, R0.63, R0.50, R0.50, R0.50, U0.50, U4.00, R0.00, R1.38, R1.13, R0.88, R0.63, R0.50, R0.50, R0.50, U0.50, U2.00, R0.00, R0.50, R0.50, R0.50, R0.50, R0.50, R0.50, R0.]50]> but was:<[R0[,00, R1,38, R1,13, R0,88, R0,63, R0,50, R0,50, R0,50, U0,50, U4,00, R0,00, R1,38, R1,13, R0,88, R0,63, R0,50, R0,50, R0,50, U0,50, U2,00, R0,00, R0,50, R0,50, R0,50, R0,50, R0,50, R0,50, R0,]50]>
  testWarmUpWithColdFactor(com.google.common.util.concurrent.RateLimiterTest): null expected:<[R0[.00, R1.75, R1.26, R0.76, R0.30, R0.20, R0.20, R0.20, U0.20, U4.00, R0.00, R1.75, R1.26, R0.76, R0.30, R0.20, R0.20, R0.20, U0.20, U1.00, R0.00, R0.20, R0.20, R0.20, R0.20, R0.20, R0.20, R0.]20]> but was:<[R0[,00, R1,75, R1,26, R0,76, R0,30, R0,20, R0,20, R0,20, U0,20, U4,00, R0,00, R1,75, R1,26, R0,76, R0,30, R0,20, R0,20, R0,20, U0,20, U1,00, R0,00, R0,20, R0,20, R0,20, R0,20, R0,20, R0,20, R0,]20]>
  testWarmUpWithColdFactor1(com.google.common.util.concurrent.RateLimiterTest): null expected:<[R0[.00, R0.20, R0.20, R0.20, R0.20, R0.20, R0.20, R0.20, U0.34, R0.00, R0.20, R0.20, R0.20, R0.20, R0.20, R0.20, R0.]20]> but was:<[R0[,00, R0,20, R0,20, R0,20, R0,20, R0,20, R0,20, R0,20, U0,34, R0,00, R0,20, R0,20, R0,20, R0,20, R0,20, R0,20, R0,]20]>
  testWarmUpAndUpdate(com.google.common.util.concurrent.RateLimiterTest): null expected:<[R0[.00, R1.38, R1.13, R0.88, R0.63, R0.50, R0.50, R0.50, U4.50, R0.00, R1.38, R1.13, R0.88, R0.34, R0.28, R0.25, R0.25, U4.25, R0.00, R0.72, R0.66, R0.59, R0.53, R0.47, R0.41, R0.34, R0.28, R0.25, R0.]25]> but was:<[R0[,00, R1,38, R1,13, R0,88, R0,63, R0,50, R0,50, R0,50, U4,50, R0,00, R1,38, R1,13, R0,88, R0,34, R0,28, R0,25, R0,25, U4,25, R0,00, R0,72, R0,66, R0,59, R0,53, R0,47, R0,41, R0,34, R0,28, R0,25, R0,]25]>
  testWarmUpAndUpdateWithColdFactor(com.google.common.util.concurrent.RateLimiterTest): null expected:<[R0[.00, R1.75, R1.26, R0.76, R0.30, R0.20, R0.20, R0.20, U4.20, R0.00, R1.75, R1.26, R0.76, R0.20, R0.10, R0.10, R0.10, U4.10, R0.00, R0.94, R0.81, R0.69, R0.57, R0.44, R0.32, R0.20, R0.10, R0.10, R0.]10]> but was:<[R0[,00, R1,75, R1,26, R0,76, R0,30, R0,20, R0,20, R0,20, U4,20, R0,00, R1,75, R1,26, R0,76, R0,20, R0,10, R0,10, R0,10, U4,10, R0,00, R0,94, R0,81, R0,69, R0,57, R0,44, R0,32, R0,20, R0,10, R0,10, R0,]10]>
  testBurstyAndUpdate(com.google.common.util.concurrent.RateLimiterTest): null expected:<[R0[.00, R1.00, R1.00, R0.50, R1.00, R2.]00]> but was:<[R0[,00, R1,00, R1,00, R0,50, R1,00, R2,]00]>
  testSimpleWeights(com.google.common.util.concurrent.RateLimiterTest): null expected:<[R0[.00, R1.00, R1.00, R2.00, R4.00, R8.]00]> but was:<[R0[,00, R1,00, R1,00, R2,00, R4,00, R8,]00]>
  testInfinity_Bursty(com.google.common.util.concurrent.RateLimiterTest): null expected:<[R0[.00, R0.00, R0.]00]> but was:<[R0[,00, R0,00, R0,]00]>
  testInfinity_BustyTimeElapsed(com.google.common.util.concurrent.RateLimiterTest): null expected:<[R0[.00, R0.00, R0.00, R0.50, R0.]50]> but was:<[R0[,00, R0,00, R0,00, R0,50, R0,]50]>
  testInfinity_WarmUp(com.google.common.util.concurrent.RateLimiterTest): null expected:<[R0[.00, R0.00, R0.]00]> but was:<[R0[,00, R0,00, R0,]00]>
  testInfinity_WarmUpTimeElapsed(com.google.common.util.concurrent.RateLimiterTest): null expected:<[R0[.00, R1.00, R1.00, R1.00, R1.]00]> but was:<[R0[,00, R1,00, R1,00, R1,00, R1,]00]>

Tests run: 597008, Failures: 16, Errors: 0, Skipped: 0
```

Does this helps you?

**Comment by cpovirk** [comment]
That's great, thanks. This does look like #1567. I'll fix that shortly.
