### ISSUE TITLE
Error running project

### ISSUE THREAD

**Issue by YuriHeupa** [google/guava#1953]
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Android SDK/build-tools/21.1.2/dx --dex --no-optimize --output app/build/intermediates/dex/debug --input-list=app/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Lcom/google/common/base/Function;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)

**Comment by JakeWharton** [comment]
This is not a problem with Guava. It is a problem with your build.

You have multiple Guava jars in your build. Only use one, or better yet, use proper Gradle dependencies which will take care of including only one and applying version resolution semantics automatically.
