### ISSUE TITLE
AbstractScheduledService.Scheduler.newFixedDelaySchedule & AbstractScheduledService.Scheduler.newFixedRateSchedule should fail fast

### ISSUE THREAD

**Issue by fror** [google/guava#1982]
Creating a Scheduler using the two existing factory methods doesn't fail fast as I've had this example of stack trace where I was extremely surprised to see none of my classes.

```
java.lang.IllegalArgumentException
	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:589)
	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleWithFixedDelay(Executors.java:738)
	at com.google.common.util.concurrent.WrappingScheduledExecutorService.scheduleWithFixedDelay(WrappingScheduledExecutorService.java:59)
	at com.google.common.util.concurrent.AbstractScheduledService$Scheduler$1.schedule(AbstractScheduledService.java:127)
	at com.google.common.util.concurrent.AbstractScheduledService$1$3.run(AbstractScheduledService.java:201)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

So please add a quick fail to those factory methods so people can properly understand what exactly is going on and why it fails. 

More comprehensively, the two factory methods should fail fast despite mentioning the  `ScheduledExecutorService.scheduleAtXxxxxRate(java.lang.Runnable, long, long, java.util.concurrent.TimeUnit)` note. I guess they should at least throw IllegalArgumentException like the delegated method does.

Here is the code I used to find the issue and which left me pondering this for a long time.
```javascript
public class AbstractScheduledServiceFastFailTest {
    @Test public void test() {
        class MyService extends AbstractScheduledService {
            int iteration = 1;
            @Override protected void runOneIteration() { iteration++; }
            @Override protected Scheduler scheduler() {
                return Scheduler.newFixedDelaySchedule(0, 0, TimeUnit.MILLISECONDS);
            }
        }
        MyService service = new MyService();
        service.addListener(new Service.Listener() {
            @Override
            public void failed(Service.State from, Throwable failure) {
                failure.printStackTrace(System.err);
            }
        }, MoreExecutors.directExecutor());
        service.startAsync();
        try { TimeUnit.SECONDS.sleep(1); } catch (InterruptedException e) { }
        Assert.assertNotEquals(1, service.iteration);
        service.stopAsync();
    }
}
```

**Comment by fror** [comment]
Thanks, that's indeed what needed to be done.
