### ISSUE TITLE
VERY strange runtime errors with com.google.common.cache.CacheBuilder

### ISSUE THREAD

**Issue by steowens** [google/guava#2363]
So it would seem that most of the Cassandra java drivers out there are using guava CacheBuilder.  I have tried Astayanx and at runtime I get:
```
Caused by: java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.build()Lcom/google/common/cache/Cache;
    at com.netflix.astyanax.thrift.ThriftKeyspaceImpl.<init>(ThriftKeyspaceImpl.java:116)
    at com.netflix.astyanax.thrift.ThriftFamilyFactory.createKeyspace(ThriftFamilyFactory.java:41)
    at com.netflix.astyanax.AstyanaxContext$Builder.buildKeyspace(AstyanaxContext.java:146)
    at com.disney.tss.auth.backend.persistence.CassandraClient.<init>(CassandraClient.java:28)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
    ... 25 more
```

I have tried the datastax driver and get a similar error in the same class CacheBuilder:

```
Caused by: java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumWeight(J)Lcom/google/common/cache/CacheBuilder;
    at com.datastax.driver.core.CodecRegistry.defaultCacheBuilder(CodecRegistry.java:305)
    at com.datastax.driver.core.CodecRegistry.<init>(CodecRegistry.java:297)
    at com.datastax.driver.core.CodecRegistry.<clinit>(CodecRegistry.java:172)
    at com.datastax.driver.core.Configuration$Builder.build(Configuration.java:276)
    at com.datastax.driver.core.Cluster$Builder.getConfiguration(Cluster.java:1221)
    at com.datastax.driver.core.Cluster.<init>(Cluster.java:116)
    at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:181)
    at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:1238)
    at com.disney.tss.auth.backend.persistence.CassandraClient.<init>(CassandraClient.java:31)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
    ... 25 more
```

When I check my maven includes and look for the "missing" methods, they are there.  But evidently google is doing something weird with class loaders or something.  More than one product that depends on this class fails inexplicably.

**Comment by ben-manes** [comment]
You are probably resolving to a very old version of Guava where `@Beta` APIs were modified. For example CacheBuilder's `maximumSize` was originally an `int` in v10 and changed to a `long` in v11.

The most common culprit in the poor pattern of uber jars, where dependencies are bundled and not shaded. If the dependency is on the classpath first, then its bundled version is resolved to even though a later one is classpath from your build tool. A classic example is JUnit v4.11 which did this with Hamcrest, resulting in many of the same annoying problems. In those cases, you have to work with your build tool to enforce that your version of the dependency comes earlier in the classpath.

**Comment by steowens** [comment]
No I am resolving to 16.0.1.  Similar errors happen when I use version 19.0.  I have been digging into the datastax code and I wonder if it has something to do with the interplay of generics.  Here is the code snippet from the datastax code that causes the stack trace above:

```java
private CacheBuilder<CacheKey, TypeCodec<?>> defaultCacheBuilder() {
        CacheBuilder<CacheKey, TypeCodec<?>> builder = CacheBuilder.newBuilder()
                // 19 primitive codecs + collections thereof = 19*3 + 19*19 = 418 codecs,
                // so let's start with roughly 1/4 of that
                .initialCapacity(100)
                .maximumWeight(1000)
                .weigher(new TypeCodecWeigher());
        if (logger.isTraceEnabled())
            // do not bother adding a listener if it will be ineffective
            builder = builder.removalListener(new TypeCodecRemovalListener());
        return builder;
    }
```
Notice they are calling newBuilder which returns a CacheBuilder<Object,Object>.  I am using Java 8.  Thoughts?

**Comment by ben-manes** [comment]
Generics are erased at compile time. My suspicion is still that while you may have the desired version in your dependency tree, the runtime version is actually much older and incompatible due to an über jar.

**Comment by steowens** [comment]
Do you suppose that the maven tomcat7 plugin under which this is executing might be the culprit?

**Comment by ben-manes** [comment]
Looks like it
https://tomcat.apache.org/maven-plugin-trunk/common-tomcat-maven-plugin/dependencies.html

**Comment by steowens** [comment]
Yep You nailed it:

```
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=1, ConflictMarker.markTime=0, ConflictMarker.nodeCount=262, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=72, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=2, ConflictResolver.conflictItemCount=184, DefaultDependencyCollector.collectTime=68, DefaultDependencyCollector.transformTime=3}
[DEBUG] org.apache.tomcat.maven:tomcat7-maven-plugin:jar:2.2:
[DEBUG]    org.apache.logging.log4j:log4j-core:jar:2.1:runtime
[DEBUG]       org.apache.logging.log4j:log4j-api:jar:2.1:runtime
[DEBUG]    org.apache.logging.log4j:log4j-slf4j-impl:jar:2.1:runtime
[DEBUG]       org.slf4j:slf4j-api:jar:1.7.5:compile
[DEBUG]    org.apache.tomcat.embed:tomcat-embed-core:jar:7.0.47:compile
[DEBUG]    org.apache.tomcat:tomcat-util:jar:7.0.47:compile
[DEBUG]    org.apache.tomcat:tomcat-coyote:jar:7.0.47:compile
[DEBUG]    org.apache.tomcat:tomcat-api:jar:7.0.47:compile
[DEBUG]    org.apache.tomcat:tomcat-jdbc:jar:7.0.47:compile
[DEBUG]    org.apache.tomcat:tomcat-dbcp:jar:7.0.47:compile
[DEBUG]    org.apache.tomcat:tomcat-servlet-api:jar:7.0.47:compile
[DEBUG]    org.apache.tomcat:tomcat-jsp-api:jar:7.0.47:compile
[DEBUG]    org.apache.tomcat:tomcat-jasper:jar:7.0.47:compile
[DEBUG]    org.apache.tomcat:tomcat-jasper-el:jar:7.0.47:compile
[DEBUG]    org.apache.tomcat:tomcat-el-api:jar:7.0.47:compile
[DEBUG]    org.apache.tomcat:tomcat-catalina:jar:7.0.47:compile
[DEBUG]    org.apache.tomcat:tomcat-tribes:jar:7.0.47:compile
[DEBUG]    org.apache.tomcat:tomcat-catalina-ha:jar:7.0.47:compile
[DEBUG]    org.apache.tomcat:tomcat-annotations-api:jar:7.0.47:compile
[DEBUG]    org.apache.tomcat:tomcat-juli:jar:7.0.47:compile
[DEBUG]    org.apache.tomcat.embed:tomcat-embed-logging-juli:jar:7.0.47:compile
[DEBUG]    org.apache.tomcat.embed:tomcat-embed-logging-log4j:jar:7.0.47:compile
[DEBUG]    org.eclipse.jdt.core.compiler:ecj:jar:4.2.2:compile
[DEBUG]    org.apache.tomcat.maven:common-tomcat-maven-plugin:jar:2.2:compile
[DEBUG]       org.apache.maven:maven-project:jar:2.2.1:compile
[DEBUG]          org.apache.maven:maven-profile:jar:2.2.1:compile
[DEBUG]          org.apache.maven:maven-artifact-manager:jar:2.2.1:compile
[DEBUG]             backport-util-concurrent:backport-util-concurrent:jar:3.1:compile
[DEBUG]          org.apache.maven:maven-plugin-registry:jar:2.2.1:compile
[DEBUG]       com.google.guava:guava:jar:10.0.1:compile
[DEBUG]          com.google.code.findbugs:jsr305:jar:1.3.9:compile
[DEBUG]       org.apache.httpcomponents:httpclient:jar:4.3.1:compile
[DEBUG]          org.apache.httpcomponents:httpcore:jar:4.3:compile
[DEBUG]          commons-logging:commons-logging:jar:1.1.3:compile
[DEBUG]       org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[DEBUG]       commons-codec:commons-codec:jar:1.6:compile
[DEBUG]    org.apache.tomcat.maven:tomcat7-war-runner:jar:2.2:compile
[DEBUG]       commons-cli:commons-cli:jar:1.2:compile
[DEBUG]    org.apache.maven:maven-plugin-api:jar:2.2.1:compile
[DEBUG]    org.apache.maven:maven-archiver:jar:2.4.2:compile
[DEBUG]       org.apache.maven:maven-artifact:jar:2.2.1:compile
[DEBUG]       org.apache.maven:maven-model:jar:2.2.1:compile
[DEBUG]       org.codehaus.plexus:plexus-interpolation:jar:1.13:compile
[DEBUG]    org.codehaus.plexus:plexus-classworlds:jar:2.2.2:compile
[DEBUG]    commons-io:commons-io:jar:2.2:compile
[DEBUG]    commons-lang:commons-lang:jar:2.6:compile
[DEBUG]    org.apache.commons:commons-compress:jar:1.4.1:compile
[DEBUG]       org.tukaani:xz:jar:1.0:compile
[DEBUG]    org.codehaus.plexus:plexus-archiver:jar:2.1.1:compile
[DEBUG]       org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile
[DEBUG]          junit:junit:jar:4.10:compile
[DEBUG]             org.hamcrest:hamcrest-core:jar:1.1:compile
[DEBUG]          classworlds:classworlds:jar:1.1-alpha-2:compile
[DEBUG]       org.codehaus.plexus:plexus-io:jar:2.0.3:compile
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:3.0.15:compile
[DEBUG]    org.apache.maven.shared:maven-filtering:jar:1.0:compile
[DEBUG]       org.apache.maven:maven-core:jar:2.2.1:compile
[DEBUG]          org.apache.maven:maven-plugin-parameter-documenter:jar:2.2.1:compile
[DEBUG]          org.apache.maven.reporting:maven-reporting-api:jar:2.2.1:compile
[DEBUG]             org.apache.maven.doxia:doxia-sink-api:jar:1.1:compile
[DEBUG]             org.apache.maven.doxia:doxia-logging-api:jar:1.1:compile
[DEBUG]          org.apache.maven:maven-repository-metadata:jar:2.2.1:compile
[DEBUG]          org.apache.maven:maven-error-diagnostics:jar:2.2.1:compile
[DEBUG]          org.apache.maven:maven-plugin-descriptor:jar:2.2.1:compile
[DEBUG]          org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4:compile
[DEBUG]          org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[DEBUG]             org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[DEBUG]       org.apache.maven:maven-monitor:jar:2.2.1:compile
[DEBUG]       org.apache.maven:maven-settings:jar:2.2.1:compile
[DEBUG]       org.sonatype.plexus:plexus-build-api:jar:0.0.4:compile
[DEBUG]    org.slf4j:jcl-over-slf4j:jar:1.7.5:compile
[DEBUG] Created new class realm plugin>org.apache.tomcat.maven:tomcat7-maven-plugin:2.2
[DEBUG] Importing foreign packages into class realm plugin>org.apache.tomcat.maven:tomcat7-maven-plugin:2.2
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>org.apache.tomcat.maven:tomcat7-maven-plugin:2.2
[DEBUG]   Included: org.apache.tomcat.maven:tomcat7-maven-plugin:jar:2.2
[DEBUG]   Included: org.apache.logging.log4j:log4j-core:jar:2.1
[DEBUG]   Included: org.apache.logging.log4j:log4j-api:jar:2.1
[DEBUG]   Included: org.apache.logging.log4j:log4j-slf4j-impl:jar:2.1
[DEBUG]   Included: org.apache.tomcat.embed:tomcat-embed-core:jar:7.0.47
[DEBUG]   Included: org.apache.tomcat:tomcat-util:jar:7.0.47
[DEBUG]   Included: org.apache.tomcat:tomcat-coyote:jar:7.0.47
[DEBUG]   Included: org.apache.tomcat:tomcat-api:jar:7.0.47
[DEBUG]   Included: org.apache.tomcat:tomcat-jdbc:jar:7.0.47
[DEBUG]   Included: org.apache.tomcat:tomcat-dbcp:jar:7.0.47
[DEBUG]   Included: org.apache.tomcat:tomcat-servlet-api:jar:7.0.47
[DEBUG]   Included: org.apache.tomcat:tomcat-jsp-api:jar:7.0.47
[DEBUG]   Included: org.apache.tomcat:tomcat-jasper:jar:7.0.47
[DEBUG]   Included: org.apache.tomcat:tomcat-jasper-el:jar:7.0.47
[DEBUG]   Included: org.apache.tomcat:tomcat-el-api:jar:7.0.47
[DEBUG]   Included: org.apache.tomcat:tomcat-catalina:jar:7.0.47
[DEBUG]   Included: org.apache.tomcat:tomcat-tribes:jar:7.0.47
[DEBUG]   Included: org.apache.tomcat:tomcat-catalina-ha:jar:7.0.47
[DEBUG]   Included: org.apache.tomcat:tomcat-annotations-api:jar:7.0.47
[DEBUG]   Included: org.apache.tomcat:tomcat-juli:jar:7.0.47
[DEBUG]   Included: org.apache.tomcat.embed:tomcat-embed-logging-juli:jar:7.0.47
[DEBUG]   Included: org.apache.tomcat.embed:tomcat-embed-logging-log4j:jar:7.0.47
[DEBUG]   Included: org.eclipse.jdt.core.compiler:ecj:jar:4.2.2
[DEBUG]   Included: org.apache.tomcat.maven:common-tomcat-maven-plugin:jar:2.2
[DEBUG]   Included: backport-util-concurrent:backport-util-concurrent:jar:3.1
[DEBUG]   Included: com.google.guava:guava:jar:10.0.1
[DEBUG]   Included: com.google.code.findbugs:jsr305:jar:1.3.9
[DEBUG]   Included: org.apache.httpcomponents:httpclient:jar:4.3.1
[DEBUG]   Included: org.apache.httpcomponents:httpcore:jar:4.3
[DEBUG]   Included: commons-logging:commons-logging:jar:1.1.3
[DEBUG]   Included: org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
[DEBUG]   Included: commons-codec:commons-codec:jar:1.6
[DEBUG]   Included: org.apache.tomcat.maven:tomcat7-war-runner:jar:2.2
[DEBUG]   Included: commons-cli:commons-cli:jar:1.2
[DEBUG]   Included: org.apache.maven:maven-archiver:jar:2.4.2
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.13
[DEBUG]   Included: commons-io:commons-io:jar:2.2
[DEBUG]   Included: commons-lang:commons-lang:jar:2.6
[DEBUG]   Included: org.apache.commons:commons-compress:jar:1.4.1
[DEBUG]   Included: org.tukaani:xz:jar:1.0
[DEBUG]   Included: org.codehaus.plexus:plexus-archiver:jar:2.1.1
[DEBUG]   Included: junit:junit:jar:4.10
[DEBUG]   Included: org.hamcrest:hamcrest-core:jar:1.1
[DEBUG]   Included: org.codehaus.plexus:plexus-io:jar:2.0.3
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.0.15
[DEBUG]   Included: org.apache.maven.shared:maven-filtering:jar:1.0
[DEBUG]   Included: org.apache.maven.reporting:maven-reporting-api:jar:2.2.1
[DEBUG]   Included: org.apache.maven.doxia:doxia-sink-api:jar:1.1
[DEBUG]   Included: org.apache.maven.doxia:doxia-logging-api:jar:1.1
[DEBUG]   Included: org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.4
[DEBUG]   Included: org.sonatype.plexus:plexus-build-api:jar:0.0.4
[DEBUG]   Included: org.slf4j:jcl-over-slf4j:jar:1.7.5
```
Now to figure out how to get the tomcat7 plugin to not pull in that old JAR.

**Comment by ben-manes** [comment]
You should be able to define a dependency section in the plugin definition. Then add a later version of Guava. In v11 the maximum weight feature was added,which explains the missing method error.

**Comment by steowens** [comment]
Yes, that did the trick. Thanks!
