### ISSUE TITLE
ClassPath.from dies on java.security.AccessControlException instead of skipping

### ISSUE THREAD

**Issue by salamanders** [google/guava#2390]
When scanning for an annotated class (in Google App Engine)

````java
final ClassLoader cl = Thread.currentThread().getContextClassLoader();
final ClassPath classPath = ClassPath.from(cl);
final ImmutableSet<ClassPath.ClassInfo> classInfos = classPath.getTopLevelClassesRecursive("com.mystuff");
```

It dies on 

```
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "ME/libs/appengine-java-sdk-1.9.32/lib/impl/agent/appengine-agentruntime.jar" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:372)
	at java.security.AccessController.checkPermission(AccessController.java:559)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkPermission(DevAppServerFactory.java:429)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at java.io.File.exists(File.java:808)
	at com.google.common.reflect.ClassPath$Scanner.scanFrom(ClassPath.java:317)
```
Shouldn't it be skipping the file instead?

**Comment by trejkaz** [comment]
It probably should just not do the File.exists check and assume that if something is on the classpath, the odds are it exists...

**Comment by eamonnmcmanus** [comment]
In that case it would blow up in the same way when it tried to open the file that it had assumed existed. I think @salamanders is right. File.exists is documented to throw SecurityException and if it does that's basically the same as the file not existing.
