### ISSUE TITLE
NullPointer when compiling with GWT 2.8 beta1 or snapshot

### ISSUE THREAD

**Issue by rsallar** [google/guava#2486]
The output log is

```
Loading modules
   cat.contesencatala.contesencatala
      Loading inherited module 'cat.contesencatala.contesencatala'
         Loading inherited module 'gwt.material.design.GwtMaterialWithJQuery'
            Loading inherited module 'gwt.material.design.GwtMaterialDesignBase'
               [WARN] Line 40: Setting configuration property named 'CssResource.legacy' in module 'gwt.material.design.GwtMaterialDesignBase' that has not been previously defined
Super Dev Mode starting up
   Loading inherited module 'cat.contesencatala.contesencatala'
      Loading inherited module 'gwt.material.design.GwtMaterialWithJQuery'
         Loading inherited module 'gwt.material.design.GwtMaterialDesignBase'
            [WARN] Line 40: Setting configuration property named 'CssResource.legacy' in module 'gwt.material.design.GwtMaterialDesignBase' that has not been previously defined
com.google.gwt.dev.jjs.InternalCompilerException: Error constructing Java AST
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.translateException(GwtAstBuilder.java:3099)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:352)
	at org.eclipse.jdt.internal.compiler.ast.AllocationExpression.traverse(AllocationExpression.java:670)
	at org.eclipse.jdt.internal.compiler.ast.Assignment.traverse(Assignment.java:260)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:347)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1379)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:3058)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:141)
	at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:384)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:470)
	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:985)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:339)
	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:580)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:513)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:499)
	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:668)
	at com.google.gwt.dev.codeserver.Recompiler.initWithoutPrecompile(Recompiler.java:200)
	at com.google.gwt.dev.codeserver.Outbox.maybePrecompile(Outbox.java:82)
	at com.google.gwt.dev.codeserver.Outbox.<init>(Outbox.java:61)
	at com.google.gwt.dev.codeserver.CodeServer.makeOutboxes(CodeServer.java:156)
	at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:118)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:91)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.gwt.dev.shell.SuperDevListener$1.run(SuperDevListener.java:84)
Caused by: java.lang.NullPointerException
	at com.google.gwt.dev.jjs.impl.ReferenceMapper.get(ReferenceMapper.java:99)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.pushNewExpression(GwtAstBuilder.java:2642)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:350)
	... 26 more

```

You can check the code here:

https://github.com/rsallar/contesencatala/tree/gwt28error

**Comment by cpovirk** [comment]
Thanks. Please report to GWT, since this appears to be an internal error in their compiler.

**Comment by rsallar** [comment]
Thx!

**Comment by cpovirk** [comment]
For my reference: https://github.com/gwtproject/gwt/issues/9351

Thanks for taking care of that.

**Comment by kevzlou7979** [comment]
I've encountered the same issue
