### ISSUE TITLE
Reduce memory usage for ContiguousSet.asList()

### ISSUE THREAD

**Issue by mfulton26** [google/guava#2725]
I was surprised to learn that `ContiguousSet.asList()` returns an `ImmutableList` which copies the discrete domain values into a new array:

```
Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at com.google.common.collect.ImmutableCollection.toArray(ImmutableCollection.java:186)
	at com.google.common.collect.ImmutableSet.createAsList(ImmutableSet.java:371)
	at com.google.common.collect.ImmutableSet.asList(ImmutableSet.java:367)
```

Can `ContiguousSet.asList()` be changed to return a subclass of `ImmutableList` which computes the values as requested instead so that a `ContiguousSet` can be viewed as a `List` to be used with methods that act on lists?

**Comment by lowasser** [comment]
`ImmutableList`s must be `RandomAccess`, and `DiscreteDomain` does not provide a mechanism to do constant-time offsets from a given start point.  Given those constraints, I don't believe this to be possible.

**Comment by jbduncan** [comment]
Hi @lowasser, what about Eclipse Collection's [`Interval`](http://www.eclipse.org/collections/javadoc/8.0.0/org/eclipse/collections/impl/list/Interval.html)?

AFAICT, it's somewhat similar to `ContiguousSet`, in that they both are lazy views over a "range" of comparable objects, one major difference being that `Interval` implements `List<Integer>` and `RandomAccess` (which makes it more similar to `ContiguousSet.asList()` API-wise), whereas `ContiguousSet` is more generic (it can work on any generic type rather than just `Integer`).

Hmm, I wonder if the fact that `Interval` works with only `Integer`s is what allows it to implement `RandomAccess`. I've not thought hard about this yet...

**Comment by lowasser** [comment]
Yes, absolutely, knowing it's a list of exactly one type that you know how to offset lets you do this.  That isn't the case for all possible DiscreteDomains, though.

**Comment by mfulton26** [comment]
Are not all discrete domains enumerable? I realize that Guava only currently defines discrete domains for `Integer`, `Long`, and `BigInteger` but what would be an example of a discrete domain for which you cannot know how to offset, etc.?

**Comment by lowasser** [comment]
I'm not certain, but DiscreteDomain doesn't currently have a method `E offset(E start, int number)`.  We could add one that just has a default implementation that does a for loop with `successor`, but this would cause existing `ContiguousSet.asList()` implementations to silently become quadratic to iterate over by index, which seems Very Bad.

**Comment by mfulton26** [comment]
Yes, I agree that a default implementation as you described would be "Very Bad" but a new `abstract C offset(C start, long number)` method could be defined on `DiscreteDomain` (`long` similar to `abstract long distance(C start, C end)`). I see that Guava allows you to create [your own DiscreteDomains ](https://github.com/google/guava/wiki/RangesExplained#your-own-discretedomains) so this would be a breaking change...

**Comment by lowasser** [comment]
We ended up doing a thing where we provided a magic private API for Guava's *own* DiscreteDomains to use that supported the "nice" ImmutableList, but we didn't expose a way for external DDs to use it. Hopefully that will alleviate the worst of the problems. https://github.com/google/guava/commit/aaae2e9a6b9cab0429f4589f89603742f28f6bd0

**Comment by shangguansb** [comment]
膜拜大神...

**Comment by jbduncan** [comment]
> 膜拜大神...

English, _s'il vous plaît_. :wink:
