### ISSUE TITLE
Non-returning waitForLoadingValue thread when no loading thread exists

### ISSUE THREAD

**Issue by toaler** [google/guava#2774]
We have an issue where a thread that lost the race to load value for the same key, is waiting infinitely, and there are no other stacks in the thread dump that indicate there is another thread doing the loading.  It seems like the loading thread failed, which I would have expected the exception to be propagated this waiting thread (only waiter), but it doesn't appear to be the case.  The stack below is present on the same thread for hours.  Unfortunately, the thread is hanging onto other valuable resources that causes a cascading series or resource saturation.  Any thoughts on how this could happen?  We are running on guava 18.0.

sun.misc.Unsafe.park
java.util.concurrent.locks.LockSupport.park
java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly
java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly
com.google.common.util.concurrent.AbstractFuture$Sync.get
com.google.common.util.concurrent.AbstractFuture.get
com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly
com.google.common.cache.LocalCache$LoadingValueReference.waitForValue
com.google.common.cache.LocalCache$Segment.waitForLoadingValue
com.google.common.cache.LocalCache$Segment.get
com.google.common.cache.LocalCache.get
com.google.common.cache.LocalCache.getOrLoad
com.google.common.cache.LocalCache$LocalLoadingCache.get
com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked
foo.bar

**Comment by ben-manes** [comment]
Can you demonstrate it in a unit test?

**Comment by DevanshiM** [comment]
Hello,

Were you able to figure out the issue?

**Comment by Veneckiy** [comment]
Hello, @ben-manes. 

I have the same problem.
I can not repeat it, load testing does not work.
But I'm using jersey for asynchronous requests, asynchronous requests are handled in quartz. The quartz has a thread pool (for example 10), and at some point the threads hang (to acquireSharedInterruptibly-> doAcquireSharedInterruptibly-> parkAndCheckInterrupt-> LockSupport.park -> Unsafe.park) and I can no longer create tasks (jobs) for the quarts.

Perhaps you have any ideas?
I have two assumptions:
1) There is a bug in guava
2) A bug in my team's project code
3) A bug in the jersey code.

**Comment by ben-manes** [comment]
Without knowing how to reproduce it, I suspect members of the Guava team won't tackle the problem until internally reported. Even then there is not much to go on to assist them, but at least they would have an environment to debug. It is also imported to ensure that you are on the latest release in case the issue was already resolved. If the problem occurs in production within a short interval then a blunt approach is to switch caching libraries (see [Caffeine](https://github.com/ben-manes/caffeine)) and see if there are any differences.

You might try to load test your route (JMeter, Gatling, etc) to see if it is reproducible. Perhaps you have a blocking call waiting on another thread, don't have a timeout, and the signal is lost due to an exception being swallowed or not handled?

**Comment by Veneckiy** [comment]
Thanks for the answer.
Repeat the error can not be due to the fact that the system is in production.
The application is multithreaded, it is possible that the developers made a mistake.
If the problem is resolved, then I'll unsubscribe here.

**Comment by prakharasthana** [comment]
@ben-manes I am also facing similar issue of lots of blocked threads, below is the stack trace. Have we fixed this in latest version of Guava or AsyncLoadingCache is the only option.
`sun.misc.Unsafe.park(boolean, long) @bci=0 (Compiled frame; information may be imprecise)
 - java.util.concurrent.locks.LockSupport.park(java.lang.Object) @bci=14, line=175 (Compiled frame)
 - com.amazon.coral.google.common.util.concurrent.AbstractFuture.get() @bci=88 (Compiled frame)
 - com.amazon.coral.google.common.util.concurrent.AbstractFuture$TrustedFuture.get() @bci=1 (Compiled frame)
 - com.amazon.coral.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(java.util.concurrent.Future) @bci=3 (Compiled frame)
 - com.amazon.coral.google.common.cache.LocalCache$LoadingValueReference.waitForValue() @bci=4 (Interpreted frame)
 - com.amazon.coral.google.common.cache.LocalCache$Segment.waitForLoadingValue(com.amazon.coral.google.common.cache.LocalCache$ReferenceEntry, java.lang.Object, com.amazon.coral.google.common.cache.LocalCache$ValueReference) @bci=37 (Interpreted frame)
 - com.amazon.coral.google.common.cache.LocalCache$Segment.get(java.lang.Object, int, com.amazon.coral.google.common.cache.CacheLoader) @bci=122 (Interpreted frame)
 - com.amazon.coral.google.common.cache.LocalCache.get(java.lang.Object, com.amazon.coral.google.common.cache.CacheLoader) @bci=17 (Interpreted frame)
 - com.amazon.coral.google.common.cache.LocalCache.getOrLoad(java.lang.Object) @bci=6 (Interpreted frame)
 - com.amazon.coral.google.common.cache.LocalCache$LocalLoadingCache.get(java.lang.Object) @bci=5 (Interpreted frame)`

**Comment by ben-manes** [comment]
I'm sorry, but I can't help directly on this. I left Google a long time ago so my discussion contributions are tolerated by the Guava team, but I can't directly assist in fixing the problems. I try to point in (hopefully) the right direction since few people are familiar with the cache's code.

Without a test case demonstrating the problem then I don't think there is much hope for a timely fix. I have not encountered it at work or in Caffeine's test suite (which also runs against Guava for compatibility checks). If we had a reproducible test then the problem could be identified.

**Comment by peiquan** [comment]
Hello, I also face the similar problem. I repeat it to load testing codes
`
    @Test
    public void testGuava() throws Exception {
        final ThreadPoolExecutor executor = new ThreadPoolExecutor(1, 1, 1, TimeUnit.MINUTES,
                new ArrayBlockingQueue<Runnable>(1),
                new ThreadPoolExecutor.DiscardPolicy());

        executor.execute(new Runnable() {
            @Override
            public void run() {
                System.out.println("run");
                while (true) {
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        });
        executor.execute(new Runnable() {
            @Override
            public void run() {
                System.out.println("run2");
                while (true) {
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        });
        final LoadingCache<Long,Long> cache = CacheBuilder.newBuilder()
                .maximumSize(10)
                .expireAfterWrite(5, TimeUnit.SECONDS)
                .refreshAfterWrite(2,TimeUnit.SECONDS)
                .build(new CacheLoader<Long, Long>() {
                    @Override
                    public Long load(Long key) throws Exception {
                        Thread.sleep(1);
                        Long temp = System.currentTimeMillis();
                        System.out.println("load " + temp);
                        return temp;
                    }

                    @Override
                    public ListenableFuture<Long> reload(final Long key, Long oldValue) throws Exception {
                        ListenableFutureTask<Long> task = ListenableFutureTask.create(new Callable<Long>() {
                            @Override
                            public Long call() throws Exception {
                                Long temp = load(key);
                                System.out.println("reload " + temp);
                                return temp;
                            }
                        });
                        executor.execute(task);
                        System.out.println("execute reload");
                        return task;
                    }
                });

        System.out.println("get " + cache.get(1L));
        Thread.sleep(3000);
        System.out.println("after 3000 get " +cache.get(1L));


        Thread.sleep(3000);
        System.out.println("after 6000 get " + cache.get(1L));

        Thread.sleep(2000);
        System.out.println("after 8000");
        System.out.println("after 8000 get " + cache.get(1L));
    }
`
I guess that the reload task is discarded,not working. To avoid that,use LinkedBlockingQueue;

**Comment by ben-manes** [comment]
Yes, an executor that discards the task will break Guava's refreshing logic. The cache avoids redundant reloads for an entry by wrapping the value with a `LoadingValueReference`, which the reload future will complete (on success or failure) and update the entry. If the executor discards the task instead, then the future will never complete and be the cache will be left in a bad state.

In this case, the old value should be be available for readers. When the oldValue has expired but a load is in progress, the caller waits for the load to complete. Thus, the reload is exposed to callers who block indefinitely. So good find and test to show the failure scenario.

I don't think this can be fixed by the cache, since the executor behavior is not communicated back. Instead the documentation could be updated to warn about this behavior requiring that the executor be allowed to eventually run the task.

**Comment by prakharasthana** [comment]
@peiquan Were you able to resolve the issue using LinkedBlockingQueue. I assume you were referring to replace ArrayBlockingQueue by LinkedBlockingQueue.

**Comment by ben-manes** [comment]
In regards to the original issue, I suspect it may be due to a [Linux kernel bug](https://github.com/torvalds/linux/commit/76835b0ebf8a7fe85beb03c75121419a7dec52f0). This is my belief having seen another [unexplained deadlock](https://gerrit-review.googlesource.com/c/gerrit/+/153090) in Gerrit, having debugged it as the cause for a similar report against Caffeine. The kernel was broken throughout 2014, so distributions may not have been updated until ~2016. If you are on a 2014-2016 distribution, you are likely affected and must upgrade. The result is that there is a lost wakeup, causing deadlocks due to missed signals, which appears to be the problem @prakharasthana and @toaler are facing.

**Comment by dineshjoshi** [comment]
@ben-manes we're running into this on macOS as well.

**Comment by pappuks** [comment]
I have faced this issue when the CacheLoader.reload() method is slow to return and the expire time has exhausted, which results in the LoadingCache.get() method being blocked till the reload finishes. This behavior somehow goes against the documentation which says that get() will not block for reload() and will instead return the old value. 

This behavior is inline with what @ben-manes has told:

>The cache avoids redundant reloads for an entry by wrapping the value with a LoadingValueReference, which the reload future will complete (on success or failure) and update the entry.



When I switched to the Caffeine cache I did not face this issue. 

Here is a gist with the test code which shows the failure with Guava cache and pass with Caffeine: https://gist.github.com/pappuks/0759041c96f938031372ad29901e2cbc

**Comment by duvalCC** [comment]
Same problem. Here is my usage:

`this.symbolExpiresCache = CacheBuilder.newBuilder()
                .maximumSize(10000)
                .expireAfterWrite(EXPIRY_EXPIRE_MINUTES, TimeUnit.MINUTES)
                .build(new CacheLoader<String, List<Long>>() {
                    @Override
                    public List<Long> load(String symbol) {
                        return loadSymbolExpires(symbol);
                    }
                });
`
 
**loadSymbolExpires(symbol)** is a method that try to fetch data from mysql，and it may costs several seconds because of the poor network.

When I looked into the jstack log , I found the same problem . Many threads were in TIMED_WAITING state. e.g:

`
"DubboServerHandler-172.28.49.8:9899-thread-64" #213 daemon prio=5 os_prio=0 tid=0x00007fd360006800 nid=0x4831 waiting on condition [0x00007fd39d05f000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000c1dd0b78> (a com.google.common.util.concurrent.AbstractFuture$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:285)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137)
        at com.google.common.cache.LocalCache$LoadingValueReference.waitForValue(LocalCache.java:3557)
        at com.google.common.cache.LocalCache$Segment.waitForLoadingValue(LocalCache.java:2302)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2191)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
        at com.mycompany.stock.rpc.service.cache.OptionCacheService.getExpiryChain(OptionCacheService.java:99)
        at com.mycompany.stock.rpc.service.UsOptionServiceImpl.getExpireDates(UsOptionServiceImpl.java:153)
        at com.mycompany.stock.rpc.service.openapi.UsOptionOpenApi.listExpirations(UsOptionOpenApi.java:71)

`

All these thread were waiting for 0x00000000c1dd0b78, but no loading thead was found.

**Comment by fuyufjh** [comment]
Same issue here. Our use case is very similar with @duvalCC 's: the loader may take hundreds of milliseconds or throw exception if network went wrong, but this cannot explain why the LoadingCache hangs on `get` forever, waiting for a future but not threads were working on it.

**Comment by agapple** [comment]
guava version 19.0

same problem but have fixed，the main reason for our scenario is jdk StackOverFlow exception

jdk 1.8 issue : https://bugs.openjdk.java.net/browse/JDK-8028686

```
public ListenableFuture<V> loadFuture(K key, CacheLoader<? super K, V> loader) {
      try {
        stopwatch.start();
        V previousValue = oldValue.get();
        if (previousValue == null) {
          V newValue = loader.load(key);  // may be StackOverFlow Exception
          return set(newValue) ? futureValue : Futures.immediateFuture(newValue);
        }
        ListenableFuture<V> newValue = loader.reload(key, previousValue);
        if (newValue == null) {
          return Futures.immediateFuture(null);
        }
        // To avoid a race, make sure the refreshed value is set into loadingValueReference
        // *before* returning newValue from the cache query.
        return transform(
            newValue,
            new com.google.common.base.Function<V, V>() {
              @Override
              public V apply(V newValue) {
                LoadingValueReference.this.set(newValue);
                return newValue;
              }
            },
            directExecutor());
      } catch (Throwable t) {
        ListenableFuture<V> result = setException(t) ? futureValue : fullyFailedFuture(t);   // may be StackOverFlow Exception
        if (t instanceof InterruptedException) {
          Thread.currentThread().interrupt();
        }
        return result;
      }
    }
```

SettableFuture.setException has skipped，caused other threads waiting SettableFuture.get() forever

Hope this answer is helpful to everyone
