### ISSUE TITLE
Streams.concat() fails with IllegalStateException

### ISSUE THREAD

**Issue by orionll** [google/guava#2781]
The following code snippet fails with IllegalStateException:
```java
Stream<Integer> stream = Arrays.asList(1).stream();
Stream<Integer> stream2 = Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8).stream();
Streams.concat(stream, stream2).parallel().toArray();
```
Stack trace:
```
Exception in thread "main" java.lang.IllegalStateException: Accept exceeded fixed size of 5
	at java.util.stream.Nodes$FixedNodeBuilder.accept(Nodes.java:1224)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at com.google.common.collect.CollectSpliterators$1FlatMapSpliterator.lambda$forEachRemaining$1(CollectSpliterators.java:246)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at com.google.common.collect.CollectSpliterators$1FlatMapSpliterator.forEachRemaining(CollectSpliterators.java:246)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2183)
	at java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2149)
	at java.util.stream.AbstractTask.compute(AbstractTask.java:316)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.Nodes.collect(Nodes.java:328)
	at java.util.stream.ReferencePipeline.evaluateToNode(ReferencePipeline.java:109)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:540)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:444)
	at org.dive.java.Example.main(Example.java:15)
```

Everything is fine if `Streams.concat` is changed to `Stream.concat`

**Comment by kevinb9n** [comment]
Thanks so much for finding and reporting this!
