### ISSUE TITLE
DirectoryNotEmptyException for desugar

### ISSUE THREAD

**Issue by rospe** [google/guava#2805]
My project on Android Studio 2.4P7 fails to build with guava 21.0. Former version of Guava works.

Details of exception:

:app:mergeProdDebugAssets UP-TO-DATE
:app:transformClassesWithDesugarForProdDebug
Exception in thread "main" java.lang.IllegalArgumentException: Interface com/google/common/base/Predicate defines non-abstract method test(Ljava/lang/Object;)Z, which is not supported
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:399)
	at com.google.devtools.build.android.desugar.Java7Compatibility.visitMethod(Java7Compatibility.java:82)
	at org.objectweb.asm.ClassVisitor.visitMethod(Unknown Source)
	at com.google.devtools.build.android.desugar.LambdaDesugaring.visitMethod(LambdaDesugaring.java:169)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:256)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDesugarForProdDebug'.
> java.nio.file.DirectoryNotEmptyException: C:\Users\Peter\AppData\Local\Temp\desugar_classpath3611760953130357256

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDesugarForProdDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: java.lang.RuntimeException: java.nio.file.DirectoryNotEmptyException: C:\Users\Peter\AppData\Local\Temp\desugar_classpath3611760953130357256
	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:186)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 20 more
Caused by: java.nio.file.DirectoryNotEmptyException: C:\Users\Peter\AppData\Local\Temp\desugar_classpath3611760953130357256
	at com.android.build.gradle.internal.transforms.DesugarTransform.removeTmpClasspathJars(DesugarTransform.java:551)
	at com.android.build.gradle.internal.transforms.DesugarTransform.transform(DesugarTransform.java:241)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:195)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:191)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	... 27 more

BUILD FAILED

**Comment by jbduncan** [comment]
Hi @rospe, I think you're having problems because Guava 21.0 requires Java 8, whereas Android only supports Java 7 (or a subset of Java 7?) so far.

The only solution to this. unfortunately, is to downgrade to 20.0 for now. When 22.0 comes out in the near future, there will be an Android specific fork that supports Java 7+ which you can use instead.

Here's what the `README.md` has to say:
> Requires JDK 1.8 or higher. If you need support for JDK 1.6 or Android, use 20.0 for now. In the next release (22.0) we will begin providing a backport for use on Android and lower JDK versions.

**Comment by rospe** [comment]
ok, thanks!
