### ISSUE TITLE
com.google.common.cache.CacheBuilderSpec

### ISSUE THREAD

**Issue by Sandesh1107** [google/guava#2836]
[2017-06-01 18:16:52,334](main)([]) ERROR - ContextLoader - Context initialization failed
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.google.common.cache.CacheBuilderSpec' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1466)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1097)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
        ... 94 common frames omitted
Wrapped by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.homeaway.ecommerce.commons.clients.PayoutVendorAccountCache': Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.f
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1148)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
        at com.homeaway.api.operations.dependencies.CommonDependencyContainer.loadBeanFactory(CommonDependencyContainer.java:166)
        at com.homeaway.api.operations.dependencies.CommonDependencyContainer.<init>(CommonDependencyContainer.java:123)
        at com.homeaway.api.operations.configuration.DefaultOperationsConfiguration.createDependencyContainer(DefaultOperationsConfiguration.java:471)
        at com.homeaway.api.operations.configuration.DefaultOperationsConfiguration.resourceServiceRegistry(DefaultOperationsConfiguration.java:324)
        at com.homeaway.api.operations.configuration.DefaultOperationsConfiguration$$EnhancerBySpringCGLIB$$a2fe5538.CGLIB$resourceServiceRegistry$22(<generated>)
        at com.homeaway.api.operations.configuration.DefaultOperationsConfiguration$$EnhancerBySpringCGLIB$$a2fe5538$$FastClassBySpringCGLIB$$461876f3.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
        at com.homeaway.api.operations.configuration.DefaultOperationsConfiguration$$EnhancerBySpringCGLIB$$a2fe5538.resourceServiceRegistry(<generated>)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) [4 skipped]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1022)

**Comment by kluever** [comment]
A stack trace without repo instructions doesn't give us much to work with...
