### ISSUE TITLE
`testScanDirectory` failures on `master` branch

### ISSUE THREAD

**Issue by eljobe** [google/guava#2845]
There is a failing test on the `master` branch. It makes it difficult to test my own changes when master isn't healthy.  This might be a problem with my environment, but I'm not sure yet, so I'm filing this issue in case others have seen it.

```
$> mvn --version
pache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T03:39:06+08:00)
Maven home: /Users/pepper/.sdkman/candidates/maven/3.5.0
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /Users/pepper/.sdkman/candidates/java/8u131/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.5", arch: "x86_64", family: "mac"

$> mvn package -e
...
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.031 sec

Results :

Tests in error: 
  testScanDirectory_symlinkCycle(com.google.common.reflect.ClassPathTest): /var/folders/hj/8mjn8yss769b4tq09bqjnlmw0000gn/T/ClassPathTest482883858389546958: unable to guarantee security of recursive delete
  testScanDirectory_symlinkToRootCycle(com.google.common.reflect.ClassPathTest): /var/folders/hj/8mjn8yss769b4tq09bqjnlmw0000gn/T/ClassPathTest3964094197949145330: unable to guarantee security of recursive delete

Tests run: 831436, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Guava Maven Parent ................................. SUCCESS [  0.140 s]
[INFO] Guava: Google Core Libraries for Java .............. SUCCESS [ 13.045 s]
[INFO] Guava Testing Library .............................. SUCCESS [ 23.493 s]
[INFO] Guava Unit Tests ................................... FAILURE [06:00 min]
[INFO] Guava GWT compatible libs .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:37 min
[INFO] Finished at: 2017-06-15T10:32:15+08:00
[INFO] Final Memory: 73M/1479M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.7.2:test (default-test) on project guava-tests: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/pepper/dev/github.com/eljobe/guava/guava-tests/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.7.2:test (default-test) on project guava-tests: There are test failures.

Please refer to /Users/pepper/dev/github.com/eljobe/guava/guava-tests/target/surefire-reports for the individual test results.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /Users/pepper/dev/github.com/eljobe/guava/guava-tests/target/surefire-reports for the individual test results.
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:74)
	at org.apache.maven.plugin.surefire.SurefirePlugin.execute(SurefirePlugin.java:642)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :guava-tests
```

I can dig into this problem for a few minutes, but it would be great if someone else can take a look who might be familiar with the tests.

**Comment by cpovirk** [comment]
That does sound environmental: Apparently your system doesn't support `SecureDirectoryStream`.

Likely we should catch exceptions from the failing `deleteRecursively` call; we don't need to fail the test just because we fail the cleanup. I can give that a shot.
