### ISSUE TITLE
Garmin lib problem

### ISSUE THREAD

**Issue by emineessid** [google/guava#3289]
Garmin lib is using guava and when i try to connect to device it throw this error ;

  java.lang.NoSuchMethodError: No static method transformAsync(Lcom/google/common/util/concurrent/ListenableFuture;Lcom/google/common/util/concurrent/AsyncFunction;)Lcom/google/common/util/concurrent/ListenableFuture; in class Lcom/google/common/util/concurrent/Futures; or its super classes (declaration of 'com.google.common.util.concurrent.Futures' appears in /data/app/com.cardio.android-8N8go_mrjaopzPPyxeHBeA==/base.apk:classes40.dex)
        at com.garmin.health.atw.pair(SourceFile:248)
        at com.garmin.health.DeviceManager.pair(SourceFile:92)
        at com.betterise.android.basemodule.module.main.mesures.garmin.GarminWatchActivity.pair(GarminWatchActivity.java:110)
        at com.betterise.android.basemodule.module.main.mesures.garmin.GarminWatchActivity.access$000(GarminWatchActivity.java:31)
        at com.betterise.android.basemodule.module.main.mesures.garmin.GarminWatchActivity$2.onScannedDevice(GarminWatchActivity.java:91)
        at com.garmin.health.GarminDeviceScanCallback.onScanResult(SourceFile:59)
        at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:555)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by Maaartinus** [comment]
Most probably, https://stackoverflow.com/a/26481352/581205 applies. As Guava gets used a lot, version conflicts are very common.

**Comment by cgdecker** [comment]
Yep, most likely multiple versions of Guava on your classpath.
