### ISSUE TITLE
ListMultimap 中得value使用clear或者删除完全部元素后出现的问题

### ISSUE THREAD

**Issue by qiaolin-li** [google/guava#3514]
代码如下：
```java
    @Test
    public void test(){
        ListMultimap<String, String> map = ArrayListMultimap.create();
        map.put("k1", "v1");
        map.put("k1", "v2");
        map.put("k2", "v1");
    
        map.asMap().forEach((k, v) ->{
            v.clear();
        });
    }

```

于是我得到这样得错误
```java
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1479)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1477)
	at com.google.common.collect.AbstractMapBasedMultimap$AsMap$AsMapIterator.next(AbstractMapBasedMultimap.java:1421)
	at com.google.common.collect.AbstractMapBasedMultimap$AsMap$AsMapIterator.next(AbstractMapBasedMultimap.java:1410)
	at java.util.Map.forEach(Map.java:620)
	at com.frxs.trade.datasyn.service.TestM.test(TestM.java:25)
```

请问下为什么删除 value 所有的元素会出现这个异常呢？

**Comment by qiaolin-li** [comment]
ListMultimap where value uses clear or deletes all elements


code show as below:
```java
    @Test
    public void test(){
        ListMultimap<String, String> map = ArrayListMultimap.create();
        map.put("k1", "v1");
        map.put("k1", "v2");
        map.put("k2", "v1");
    
        map.asMap().forEach((k, v) ->{
            v.clear();
        });
    }
```


So I got this exception

```java
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1479)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1477)
	at com.google.common.collect.AbstractMapBasedMultimap$AsMap$AsMapIterator.next(AbstractMapBasedMultimap.java:1421)
	at com.google.common.collect.AbstractMapBasedMultimap$AsMap$AsMapIterator.next(AbstractMapBasedMultimap.java:1410)
	at java.util.Map.forEach(Map.java:620)
	at com.frxs.trade.datasyn.service.TestM.test(TestM.java:25)
```


May I ask why deleting all the elements of value will cause this exception?

**Comment by Grypse** [comment]
It looks like using HashMap within ListMutimap. It recall the Iterator
method When u delete value and cause the ConcurrentModificationException.

**Comment by qiaolin-li** [comment]
thanks

**Comment by nglorioso** [comment]
It sounds like you've got the answer you're looking for. In the future, you might be able to get a better answer on StackOverflow: https://stackoverflow.com/questions/tagged/guava
