### ISSUE TITLE
Maven-surefire-plugin memory leak after upgrade

### ISSUE THREAD

**Issue by WilliamCollishaw** [google/guava#3524]
[Support for JDK 11](https://issues.apache.org/jira/browse/SUREFIRE-1562) was officially complete for the maven-surefire-plugin version [2.22.1](https://blogs.apache.org/maven/entry/apache-maven-surefire-plugin-version1). 

Version [2.17](https://blog.soebes.de/blog/2014/03/16/apache-maven-surefire-plugin-2-dot-17-released/) runs as expected, however using any version, [2.18](https://blog.soebes.de/blog/2014/11/08/apache-maven-surefire-version-2-dot-18-released/) and above, results in the following out of memory exceptions:

```Running com.google.common.collect.testing.FeatureSpecificTestSuiteBuilderTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in com.google.common.collect.testing.FeatureSpecificTestSuiteBuilderTest
Running com.google.common.collect.testing.HelpersTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.google.common.collect.testing.HelpersTest
Running com.google.common.collect.testing.IteratorTesterTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.google.common.collect.testing.IteratorTesterTest
Running com.google.common.collect.testing.MapTestSuiteBuilderTests
Tests run: 1811, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.346 sec - in com.google.common.collect.testing.MapTestSuiteBuilderTests
Running com.google.common.collect.testing.MinimalCollectionTest
Tests run: 151, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.google.common.collect.testing.MinimalCollectionTest
Running com.google.common.collect.testing.MinimalIterableTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.google.common.collect.testing.MinimalIterableTest
Running com.google.common.collect.testing.MinimalSetTest
Tests run: 185, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.google.common.collect.testing.MinimalSetTest
Running com.google.common.collect.testing.OpenJdk6ListTests
Tests run: 6797, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.426 sec - in com.google.common.collect.testing.OpenJdk6ListTests
Running com.google.common.collect.testing.OpenJdk6MapTests
Tests run: 320533, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 44.664 sec - in com.google.common.collect.testing.OpenJdk6MapTests
Running com.google.common.collect.testing.OpenJdk6QueueTests
Exception in thread "Thread-33" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:596)
	at java.lang.StringBuffer.append(StringBuffer.java:367)
	at java.io.BufferedReader.readLine(BufferedReader.java:370)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.StreamPumper.run(StreamPumper.java:66)
```

**Comment by ronshapiro** [comment]
Is this a bug for Guava, or for the surefire plugin?

**Comment by WilliamCollishaw** [comment]
This appears to be caused by [SUREFIRE-1147](https://issues.apache.org/jira/projects/SUREFIRE/issues/SUREFIRE-1147), reported in 2015 and there does not appear to be any sign of this being fixed in the near future. That Jira item has the following comment:

> I believe the appropriate term here is "unbounded memory usage", not memory leak as such. Also, while I am sure some things can be done to alleviate the problem, I am not really sure we will ever come to the point where you can run a single test class an "indefinite" number of times.

This comment leads me to believe the fix should be splitting the JDK6 tests into smaller subsets
