### ISSUE TITLE
cache init throw ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by sunnywuco** [google/guava#3969]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 195
        at com.google.common.cache.CacheBuilder.<clinit>(CacheBuilder.java:164) ~[guava-29.0-jre.jar:?]
        at com.cache.PermissionCache.<clinit>(PermissionCache.java:15) ~[classes/:?]
        at com.cache.PermissionCacheUtil.refreshSwitchStatus(PermissionCacheUtil.java:78)

**Comment by cpovirk** [comment]
Interesting. I don't see an array index on line 164 of any release of `guava` (either `jre` or `android`) -- in particular, [not in 29.0-jre](https://github.com/google/guava/blob/v29.0/guava/src/com/google/common/cache/CacheBuilder.java#L164).

I'm not sure what might be wrong here, but I don't think we have any way to help :(
