### ISSUE TITLE
UnsupportedOperationException when modify TreeRangeSet.subRangeSet(Range)

### ISSUE THREAD

**Issue by zhanhb** [google/guava#4002]
Unable to modify subRangeSet returned by TreeRangeSet.subRangeSet(Range).
IMO, it should be availiable to do so as specified in the document.

```java
import com.google.common.collect.Range;
import com.google.common.collect.TreeRangeSet;
import org.junit.jupiter.api.Test;

@SuppressWarnings("UnstableApiUsage")
public class SubRangeSetTest {

    @Test
    public void testAdd() {
        TreeRangeSet<Integer> set = TreeRangeSet.create();
        Range<Integer> range = Range.closedOpen(0, 5);
        set.subRangeSet(range).add(range);
    }

    @Test
    public void testReplaceAdd() {
        TreeRangeSet<Integer> set = TreeRangeSet.create();
        Range<Integer> range = Range.closedOpen(0, 5);
        set.add(range);
        set.subRangeSet(range).add(range);
    }
}
```

```
java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractMap.put(AbstractMap.java:209)
	at com.google.common.collect.TreeRangeSet.replaceRangeWithSameLowerBound(TreeRangeSet.java:266)
	at com.google.common.collect.TreeRangeSet.add(TreeRangeSet.java:216)
	at com.google.common.collect.TreeRangeSet$SubRangeSet.add(TreeRangeSet.java:894)
	at SubRangeSetTest.testAdd(SubRangeSetTest.java:12)
```
```
java.lang.UnsupportedOperationException
	at com.google.common.collect.UnmodifiableIterator.remove(UnmodifiableIterator.java:46)
	at com.google.common.collect.Iterators.clear(Iterators.java:985)
	at com.google.common.collect.Maps$IteratorBasedAbstractMap.clear(Maps.java:3562)
	at com.google.common.collect.TreeRangeSet.add(TreeRangeSet.java:214)
	at com.google.common.collect.TreeRangeSet$SubRangeSet.add(TreeRangeSet.java:894)
	at SubRangeSetTest.testReplaceAdd(SubRangeSetTest.java:20)
```

**Comment by cpovirk** [comment]
Thanks, that sounds like a bug to me, too.

I see a slightly different stack trace (with both guava-29.0-jre.jar and guava-29.0-android.jar), so the exact failure may depend on the Guava version:

```
# -jre
Exception in thread "main" java.lang.UnsupportedOperationException
  at java.base/java.util.AbstractMap.put(AbstractMap.java:209)
  at com.google.common.collect.TreeRangeSet.replaceRangeWithSameLowerBound(TreeRangeSet.java:266)
  at com.google.common.collect.TreeRangeSet.add(TreeRangeSet.java:216)
  at com.google.common.collect.TreeRangeSet$SubRangeSet.add(TreeRangeSet.java:894)
  at Issue4002.main(Issue4002.java:8)

# -android
Exception in thread "main" java.lang.UnsupportedOperationException
  at java.base/java.util.AbstractMap.put(AbstractMap.java:209)
  at com.google.common.collect.TreeRangeSet.replaceRangeWithSameLowerBound(TreeRangeSet.java:268)
  at com.google.common.collect.TreeRangeSet.add(TreeRangeSet.java:218)
  at com.google.common.collect.TreeRangeSet$SubRangeSet.add(TreeRangeSet.java:899)
  at Issue4002.main(Issue4002.java:8)
```

Sorry for the trouble. We will have a look.

**Comment by cpovirk** [comment]
Presumably because we don't implement `put` in `SubRangeSetRangesByLowerBound`.

**Comment by zhanhb** [comment]
This is a stacktrace of subRangeSet.remove. It should meet the same stacktrace over all guava versions.

**Comment by cpovirk** [comment]
Oh, thanks, I pasted from the email (which has the original text from your post). It's good to know that both add _and_ remove fail.

**Comment by zhanhb** [comment]
The codes and stacktraces updated.

**Comment by cpovirk** [comment]
`subRangeSet` was part of the initial `RangeSet` in Guava 14.0. Calling `add` against that version, I get a `StackOverflowError`... :) I haven't checked whether `add` worked in some intermediate version.

`remove` at least is a successful no-op under 14.0. So that's a definite regression.

**Comment by cpovirk** [comment]
Oh, sorry, you're saying that `remove` is OK but that `add` is broken -- both in the case in which `add` has to remove an existing range and in the case in which it doesn't.

**Comment by cpovirk** [comment]
(`add` is broken at least as far back as Guava 20.0.)
