### ISSUE TITLE
AssertionError from Range.gap

### ISSUE THREAD

**Issue by cpovirk** [google/guava#4004]
@zhanhb [reports](https://github.com/google/guava/commit/a9dd7098f741d652fe2daf8193b831737dc36aa0#commitcomment-41940819):

```java
Range.atLeast(1).gap(Range.atLeast(2));
```
```txt
java.lang.AssertionError
	at com.google.common.collect.Cut$AboveAll.describeAsLowerBound(Cut.java:259)
	at com.google.common.collect.Range.toString(Range.java:674)
	at com.google.common.collect.Range.<init>(Range.java:357)
	at com.google.common.collect.Range.create(Range.java:155)
	at com.google.common.collect.Range.gap(Range.java:582)
```

**Comment by Koooooo-7** [comment]
Close via #4030 .
