### ISSUE TITLE
TreeMultimap.get(null) triggers NullPointerException

### ISSUE THREAD

**Issue by AnkBurov** [google/guava#5460]
Hello. Executing of such code triggers NPE:
```java
TreeMultimap.create().get(null);
```
```
Exception in thread "main" java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
	at com.google.common.collect.NaturalOrdering.compare(NaturalOrdering.java:36)
	at com.google.common.collect.NaturalOrdering.compare(NaturalOrdering.java:26)
	at com.google.common.collect.TreeMultimap.createCollection(TreeMultimap.java:143)
	at com.google.common.collect.AbstractMapBasedMultimap.get(AbstractMapBasedMultimap.java:291)
	at com.google.common.collect.AbstractSetMultimap.get(AbstractSetMultimap.java:75)
	at com.google.common.collect.AbstractSortedSetMultimap.get(AbstractSortedSetMultimap.java:87)
	at com.google.common.collect.TreeMultimap.get(TreeMultimap.java:167)
```

According to method's javadoc, an empty collections should be returned:
```
Returns a collection view of all values associated with a key. If no mappings in the multimap
have the provided key, an empty collection is returned.
```
but instead an NPE is thrown.

As a fix, may be it is worth to remove `keyComparator().compare(key, key)` invocation in `com.google.common.collect.TreeMultimap#createCollection(K)` and invoke simply `super.createCollection(key)`?

**Comment by perceptron8** [comment]
It is already documented in TreeMultimap's javadoc:
> Implementation of Multimap whose keys and values are ordered by their natural ordering or by supplied comparators. In all cases, this implementation uses Comparable.compareTo(T) or Comparator.compare(T, T) instead of Object.equals(java.lang.Object) to determine equivalence of instances.
(https://guava.dev/TreeMultimap)

It is inevitable to use comparator to determine equality.

Please note that the following also triggers NPE:

```
Map<Integer, Integer> map = new TreeMap<>();
map.get(null);
```

**Comment by cpovirk** [comment]
I'm happy to see that we do document this. Also relevant:

> Null keys and values are permitted (provided, of course, that the respective comparators support them).

Still, it's unfortunate that [`get`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/collect/TreeMultimap.html#get(K)) is annotated as accepting a `@Nullable K` rather than just a `K`. Luckily, _this quarter_ is the one in which we're finally planning to redo Guava's nullness annotations to make them more useful. That should include the change to require `K` here. (Of course, that still is "just documentation," except for users who run a nullness checker.)

Arguably it would still make sense to document the possible `NullPointerException`. In general, we don't document `@throws NullPointerException if param is null` because it's assumed for any parameter without `@Nullable`: Our packages are annotated with `@ParametersAreNonNullByDefault` ([example](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/base/package-summary.html)). However:

- This parameter _is_ annotated with `@Nullable` (though, again, we'll fix that soon).
- This case is slightly unusual because the method does not _necessarily_ throw: The behavior depends on the contract of the `Comparator`.

I will leave this issue open as a low-priority potential change to documentation. That's in addition to the high-priority work to improve the nullness annotations.

**Comment by AnkBurov** [comment]
Not sure why there is even a need to use comparator in the case when key is null especially when the returned value is ignored and the only needed thing here is to create an empty collection, but if you say that this is expected behavior - ok, I'll just override the method and invoke `createCollection()` when key is null. 

Thanks. You can close the issue if you want.
