### ISSUE TITLE
When will Guava support Java 16?

### ISSUE THREAD

**Issue by danielalmeidagoncalves** [google/guava#5577]
Hi all, 

In our project we would like to upgrade our java version to version 16 (release in March this year) but it seems that Guava is breaking if we try to do the upgrade. We get the following error:

```java
INFO: An exception was caught and reported. Message: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.Prote
ctionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2a742aa2
java.lang.IllegalStateException: Unable to load cache item
        at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:79)
```

Is this about has someone said, trying to access classes that are now part of JDK internals? What are the plans for supporting JDK 16?

Thanks in advance!

**Comment by kashike** [comment]
> at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:79)

You should be poking at [the guice repository](https://github.com/google/guice/) for this - not caused by guava.
