### ISSUE TITLE
Issue with Android 12, api 31 , while building chromium code 

### ISSUE THREAD

**Issue by gauravwalia2013** [google/guava#5703]
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
	at com.android.manifmerger.ManifestMerger2.<clinit>(ManifestMerger2.java:83)
	at com.android.manifmerger.Merger.createInvoker(Merger.java:190)
	at com.android.manifmerger.Merger.process(Merger.java:94)
	at com.android.manifmerger.Merger.main(Merger.java:42)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 4 more

**Comment by amalloy** [comment]
There is insufficient information in this issue for us to take any action. Apparently something somewhere can't find Guava. This seems unlikely to be a Guava issue, since Guava couldn't even be found on the classpath. But if you have clear reproduction steps that point to this being a Guava issue, please include them when you reopen this issue.
