### ISSUE TITLE
NoSuchMethodError: com.google.common.collect.ImmutableMap$Builder.buildOrThrow() in v31.1

### ISSUE THREAD

**Issue by ataylormays-duetto** [google/guava#6002]
Our codebase was previously using `compile 'com.google.guava:guava:31.0.1-jre'`. After updating to `compile 'com.google.guava:guava:31.1-jre'`, we started seeing the following error triggered from a class that uses an ImmutableTable.Builder while executing tests:

```
java.lang.NoSuchMethodError: com.google.common.collect.ImmutableMap$Builder.buildOrThrow()Lcom/google/common/collect/ImmutableMap;
	at com.google.common.collect.SparseImmutableTable.<init>(SparseImmutableTable.java:85) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.SparseImmutableTable.<clinit>(SparseImmutableTable.java:32) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableTable.forOrderedComponents(RegularImmutableTable.java:167) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableTable.forCellsInternal(RegularImmutableTable.java:155) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableTable.forCells(RegularImmutableTable.java:127) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableTable$Builder.buildOrThrow(ImmutableTable.java:288) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableTable$Builder.build(ImmutableTable.java:270) ~[guava-31.1-jre.jar:?]
	at com.duetto.types.TypedRegistry$Builder.build(TypedRegistry.java:60) ~[tools-1.0.jar:?]
```

I initially thought this was due to conflicting versions of Guava, but checking the Gradle's dependencyInsight tool shows just the single upgraded 31.1 version of Guava: 

```
./gradlew -q capture:dependencyInsight --dependency com.google.guava:guava 
setting extraProdArgs for java 8.  jdkMode '1.8'
com.google.guava:guava:31.1-jre
   variant "compile" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-api
      org.gradle.libraryelements     = jar (compatible with: classes)
      org.gradle.category            = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 8
   ]

com.google.guava:guava:31.1-jre
\--- project :tools
     +--- compileClasspath
     +--- project :scheduler
     |    \--- compileClasspath
     +--- project :gacks
     |    \--- project :scheduler (*)
     +--- project :spring
     |    +--- project :scheduler (*)
     |    \--- project :gacks (*)
     \--- project :data
          +--- compileClasspath
          +--- project :scheduler (*)
          +--- project :server
          |    \--- compileClasspath
          +--- project :gacks (*)
          +--- project :spring (*)
          \--- project :mailer
               \--- project :gacks (*)

(*) - dependencies omitted (listed previously)
```

**Comment by nick-someone** [comment]
```shell
wget https://repo1.maven.org/maven2/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
javap -cp guava-31.1-jre.jar 'com.google.common.collect.ImmutableMap$Builder'
Compiled from "ImmutableMap.java"
public class com.google.common.collect.ImmutableMap$Builder<K, V> {
  java.util.Comparator<? super V> valueComparator;
  java.util.Map$Entry<K, V>[] entries;
  int size;
  boolean entriesUsed;
  public com.google.common.collect.ImmutableMap$Builder();
  com.google.common.collect.ImmutableMap$Builder(int);
  public com.google.common.collect.ImmutableMap$Builder<K, V> put(K, V);
  public com.google.common.collect.ImmutableMap$Builder<K, V> put(java.util.Map$Entry<? extends K, ? extends V>);
  public com.google.common.collect.ImmutableMap$Builder<K, V> putAll(java.util.Map<? extends K, ? extends V>);
  public com.google.common.collect.ImmutableMap$Builder<K, V> putAll(java.lang.Iterable<? extends java.util.Map$Entry<? extends K, ? extends V>>);
  public com.google.common.collect.ImmutableMap$Builder<K, V> orderEntriesByValue(java.util.Comparator<? super V>);
  com.google.common.collect.ImmutableMap$Builder<K, V> combine(com.google.common.collect.ImmutableMap$Builder<K, V>);
  public com.google.common.collect.ImmutableMap<K, V> build();
  public com.google.common.collect.ImmutableMap<K, V> buildOrThrow();
  public com.google.common.collect.ImmutableMap<K, V> buildKeepingLast();
  com.google.common.collect.ImmutableMap<K, V> buildJdkBacked();
}
```

I'm not sure how to help debug this one further, as `public com.google.common.collect.ImmutableMap<K, V> buildOrThrow();` is definitively a member of the ImmutableMap class inside the guava jar.

Can you see if there are other dependencies on your class doing really weird things like re-declaring this class?

**Comment by eamonnmcmanus** [comment]
If you control the `TypedRegistry` class, it could be useful to put this in a static initializer:

```java
  for (Class<?> c : new Class[] {ImmutableMap.class, ImmutableTable.class}) {
    System.out.printf("%s comes from %s\n", c.getName(), c.getProtectionDomain().getCodeSource().getLocation());
  }
```

My suspicion is that maybe a version of `ImmutableMap` is being picked up from some source that doesn't also define `ImmutableTable`.

**Comment by ataylormays-duetto** [comment]
Aha, thanks so much for the tip @eamonnmcmanus - you're right it looks like the ImmutableMap is coming from the Google closure-compiler:

```
com.google.common.collect.ImmutableMap comes from file:/Users/ataylormays/dev/duetto/capture/build/install/capture/lib/closure-compiler-v20190301.jar
com.google.common.collect.ImmutableTable comes from file:/Users/ataylormays/dev/duetto/capture/build/install/capture/lib/guava-31.1-jre.jar
```

Not sure why the closure-compiler includes the Guava classes in its JAR.

**Comment by ataylormays-duetto** [comment]
This was resolved by updating the closer-compiler from v20190301 -> v20220405. Thanks for the help in tracking it down @eamonnmcmanus !
