### ISSUE TITLE
Include Error Prone Setup for IntelliJ IDEA Setup in README.md

### ISSUE THREAD

**Issue by stephenspol** [google/guava#6167]
There was no mention in the `README.md` regarding setup for `errorprone`. This will caused java to throw a `java: Compilation failed: internal java compiler error` when trying to run code in Intellij.

Stacktrace error message:
`Error:java: Caused by: java.lang.NoSuchMethodError: com.sun.tools.javac.util.JavacMessages.add(Lcom/sun/tools/javac/util/JavacMessages$ResourceBundleHelper;)V
Error:java: 	at com.google.errorprone.BaseErrorProneJavaCompiler.setupMessageBundle(BaseErrorProneJavaCompiler.java:202)
Error:java: 	at com.google.errorprone.ErrorProneJavacPlugin.init(ErrorProneJavacPlugin.java:40)`

Solution: 
Include a section in the README discussing the process to setup Error Prone plugin when using Intellij. It did not appear that support for eclipse existed but a section can be added when it is supported.

Solution Link: https://errorprone.info/docs/installation#intellij-idea

I would be more than happy to contribute to this issue.

**Comment by itsAfnanAlam** [comment]
Hi, can I work on this?
