### ISSUE TITLE
Support Sets.toImmutableEnumSet() on Android

### ISSUE THREAD

**Issue by swankjesse** [google/guava#6567]
When we upgraded Truth we started getting crashes like this:

```
java.lang.NoSuchMethodError: 'java.util.stream.Collector com.google.common.collect.Sets.toImmutableEnumSet()'
	at com.android.resources.ResourceType.<clinit>(ResourceType.java:175)
	at app.cash.paparazzi.internal.DynamicResourceIdManager$IdProvider.<init>(DynamicResourceIdManager.kt:14)
	at app.cash.paparazzi.internal.DynamicResourceIdManager.<init>(DynamicResourceIdManager.kt:28)
	at app.cash.paparazzi.internal.PaparazziCallback.<init>(PaparazziCallback.kt:52)
	at app.cash.paparazzi.Paparazzi.prepare(Paparazzi.kt:145)
	at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:116)
```

As @TWiStErRob explains on [Paparazzi #906](https://github.com/cashapp/paparazzi/issues/906):

> This came back in Truth 1.1.5 because Paparazzi depends on 32.0.0-jre vs Truth uses 32.0.1-android, and the higher version number wins. Looks like the workaround has to stay.

A very simple fix for our problem is for Guava to support the `toImmutableEnumSet()` function on all platforms. I don’t believe this function needs the same implementation on all platforms; it just needs something so we don’t crash at runtime.

**Comment by cpovirk** [comment]
Sorry, this kind of problem crops up occasionally. See, e.g., https://stackoverflow.com/q/65646026/28465.

Since we dropped support for Java 7 back in [31.0](https://github.com/google/guava/releases/tag/v31.0), we can in theory now get away with adding methods that use Java 8+ types like `Collector` in their signatures. That's true even if Android users don't use library desugaring. (And I'm not sure we could require them to use it yet. [Issue 203113147](https://issuetracker.google.com/203113147) would help but probably not be sufficient).) Thankfully, we can rely on the Android VM to ignore those methods unless someone actually calls them. (And maybe we can use `@RequiresApi` to prevent people from calling them by accident. But that may annoy people who target older versions of Android but use library desugaring (since Android Lint would still report an error for calls to the method, even though it's actually safe for them). And maybe the `androidx.annotation:annotation-jvm` dependency would become another obstacle to [modularization](https://github.com/google/guava/issues/2970)? But this is becoming a long digression.)

Can we get away with it _in practice_? I'm going to run a test with `toImmutableEnumSet()` specifically to see what happens. I do know that we've seen trouble when testing another Java 8+ thing—specifically, adding one `default` method, which I might have guessed would be _easier_ than adding methods that use Java 8+ APIs. But adding _another_ `default` method appeared to work fine.... We're never going to feel _completely_ safe with making these kinds of changes, but we'll have to take the plunge eventually. We took a baby step in this direction by adding a usage of a class that isn't supported on Android _at all_ in [32.0.0](https://github.com/google/guava/releases/tag/v32.0.0) (namely, a usage of `AnnotatedType`). That _seems_ to have gone OK so far.

I do note that this general class of problem will exist as long as guava-jre contains _any_ APIs that guava-android doesn't. And I'm unsure whether the two will fully converge. But this problem is a reason to consider _making_ them converge, even if it doesn't make fully sense. And even if they don't fully converge, there's a big difference between missing commonly used APIs (like our `Collector` implementations) and missing only the more obscure things.

Independent of all that, one thing that we really, really should do is finally get back to https://github.com/google/guava/pull/3683: It is designed to make Gradle pick the maximum _numeric_ part of the version number for Guava but then choose -android or -jre as appropriate. That PR is frequently on my mind; I just need to find an hour on a day when I'm feeling up for a deep dive and when nothing else is on fire :)

(For non-Gradle users, we could additionally consider releasing separate `truth-android` and `truth-jre` artifacts, which would have identical class files but would have a different Guava dep. (I wonder if any tools had to go to effort to specifically recognize Guava's unusual version numbers, and I wonder if a similar change in Truth would cause them similar issues. And I wonder if the Truth change would "look bad" even if it turned out to be a net win in fighting the Guava problem.... For anyone else at Google following along, see bug 177249370.)

**Comment by cpovirk** [comment]
It looks like we'd be able to add `toImmutableEnumSet()` to `guava-android` without breaking anything inside Google.

I'm thinking I might try something like this:
- Pick a less commonly used class (`ImmutableTable`?) whose Java 8+ methods we could add to guava-android. (Bonus: The relevant `ImmutableTable` methods return a `Collector`, so users are unlikely to call the methods unless they're also using other Java 8+ APIs. This means that we can probably count on existing `NewApi` enforcement without having to use `@RequiresApi` ourselves. And really, the `Collector` APIs are probably a sizable portion of what users want, so it's good to try adding one of them.)
- Try actually submitting that internally and seeing it get used.
- Consider repeating that for other APIs.
- Release the first such API publicly.
- If all goes well, do more of that, thinking more about `@RequiresApi`.

I don't expect to add any of the APIs in the next Guava release. But that's only because we've had a surprising number of changes that I'd like to release soonish so that users can pick them out without taking even a small risk from `ImmutableTable.toImmutableTable` (or whatever we end up adding). But we won't need to wait a year before releasing again :)

(I'm going to generalize this issue to be about the overall effort.)

**Comment by cpovirk** [comment]
Actually, we added `Stopwatch.elapsed()` (which returns a Java 8 `Duration`) to our internal Android copy a while back, but I'd forgotten. It's gone well. But I'd note that we added special support to our Java compatibility enforcement (in [this change to `AndroidJdkLibsChecker`](https://github.com/google/error-prone/commit/be2daa56527de202af4dbc440af37d2b310b3495)), so we might want similar enforcement for future changes (albeit perhaps not for `Collector` APIs, given what I said above).

**Comment by TWiStErRob** [comment]
@swankjesse, from my reading the original issue will be solved by https://github.com/google/guava/commit/ce78fc67cb8b72621e2d1154e8b8b343be97abd0, see the section titled "Selecting the appropriate flavor" in [32.1 release notes](https://github.com/google/guava/releases/tag/v32.1.0), will test when 32.1.1 is released.

**Comment by TWiStErRob** [comment]
Not trivial... got a capability conflict, will have to look deeper later.

**Comment by cpovirk** [comment]
(Another testing step I should take here is to publish one release with the new APIs present but package-private.)

**Comment by cpovirk** [comment]
I was just reminded that people see problems sometimes on the annotation-processor classpath when guava-android sneaks in. (I believe Dagger, for example, still [avoids our `Collector` APIs](https://github.com/google/dagger/blob/master/java/dagger/internal/codegen/extension/DaggerStreams.java) for that reason.)

Anyway, my hope now is to:
1. back out https://github.com/google/guava/commit/945ce37fd615ae976f4aefc40df8d2f4b67acf5e (which I don't think we actually need)
2. add the new `Collector` APIs as package-private (so that no one can come to depend on them yet but so that we have a chance to shake out problems that might arise)
3. cut a release
4. if all goes well, promote the `Collector` APIs to `public` but with `@Beta` (but really hope that we don't have to back them out)
5. cut another release
6. if all goes well, start adding other Java 8 APIs

I still kind of expect that to blow up for someone somehow, probably on account of performing reflection on our classes. My hope would be that anyone who is in a position to use reflection would also be in a position to enable library desugaring. But that's why we'd run the test... :)

**Comment by cpovirk** [comment]
I got to experience the `NoSuchMethodError` issue myself again with a few projects (Gradle and Bazel) when I updated them to Truth 1.3.0.

The plan is still to add the APIs to `guava-android`. And back in December, I published https://github.com/google/guava/releases/tag/v33.0.0 to add some as package-private to shake out any problems that might arise.

If your friends use `guava-android` but haven't updated to 33.0.0 yet, please encourage them to do so and then to report any problems. If we don't hear of problems, I'll start exposing APIs publicly. That should help with the `NoSuchMethodError` issue, and it should be useful to Android developers for its own sake.

**Comment by cpovirk** [comment]
[33.2.0](https://github.com/google/guava/releases/tag/v33.2.0) adds `Collector` APIs, including [`Sets.immutableEnumSet`](https://guava.dev/releases/33.2.0-android/api/docs/com/google/common/collect/Sets.html#toImmutableEnumSet()), to `guava-android`.

Barring surprises, we'll add most Java 8+ APIs in the next release or thereafter.

**Comment by cpovirk** [comment]
[Guava 33.4.0](https://github.com/google/guava/releases/tag/v33.4.0) added almost everything that was still missing.

The main exceptions are that we haven't added (a) `default` methods and (b) supertypes for classes like our `Function`. I hope to be able to do both of those someday, but I want to find time to better understand some problems that we've seen with such changes in very unusual cases internally. (I think those cases are Just Wrong, but I don't want to add anything to Guava that we might end up having to remove if problems surface later.)

Let me know if there's anything in particular that you need that isn't available (where it's from my list of "main exceptions" or not).
