### ISSUE TITLE
Inheriting Javadoc from the JDK is broken (as was _linking to_ the JDK)

### ISSUE THREAD

**Issue by cpovirk** [google/guava#6790]
e.g., https://guava.dev/BiMap has blank descriptions for `put`, `putAll`, and `values`, and it has no links for types like `java.lang.Object` and `java.util.Map`

**Comment by cpovirk** [comment]
I can reproduce this locally with `./mvnw clean javadoc:javadoc` with `JAVA_HOME` pointed to Java 11. I can also reproduce it with `mvn`, so it's not likely to be related to my recent Maven Wrapper change.

**Comment by cpovirk** [comment]
The info disappeared at https://github.com/google/guava/commit/bdbcb3796172d286238d61c75480d595d971ef93, so it's been almost a year :\

A change from around that time that looks plausibly related is https://github.com/google/guava/commit/8a676ade617c6be992165cd0658779a14acef2f2. I could believe that the cause is `java.specification.version`.

**Comment by cpovirk** [comment]
Yes, I can fix it by removing the `java.specification.version` change. But that point, Javadoc prints a bunch of warnings under JDK 11, and it fails entirely (or at least pretty badly) under JDK 17.

I could believe that the problem is somehow related to modules. Roughly, the JDK sources might be "hidden" by the JDK modules?

I briefly tried messing with the path we pass to Javadoc, passing `${project.build.directory}/jdk-sources/java.base` instead of just `${project.build.directory}/jdk-sources`, but that didn't help.

I tried removing our exclusion of the JDK's `module-info` files, but then I got:

```
[ERROR] Creating an aggregated report for both named and unnamed modules is not possible.
[ERROR] Ensure that every module has a module descriptor or is a jar with a MANIFEST.MF containing an Automatic-Module-Name.
[ERROR] Fix the following projects:
[ERROR]  - com.google.guava:guava
```

So it's possible that things would go better if Guava were a real module (https://github.com/google/guava/issues/2970). (_Presumably_ Javadoc would be willing to inherit Javadoc across module boundaries.)

I could probably "fix" this by setting the Javadoc source version back to 8 for JDK 11 (where we know that it works). But we know that it doesn't work for JDK 17, so this would be only a temporary fix.

**Comment by cpovirk** [comment]
> (_Presumably_ Javadoc would be willing to inherit Javadoc across module boundaries.)

I guess I'm _somewhat_ pessimistic about that, given that the sources probably are being hidden entirely.

But I could believe that we could do something with `--patch-module` or something. And in fact, after poking around a little, I found https://bugs.openjdk.org/browse/JDK-8300694. (That bug even notes that this worked for Guava at the latest release but not at head at the time :))

I'm not excited about trying to get this to work, but if anyone wants to try to wire it up, either the temporary solution of using `<source>8</source>` under JDK11 or the permanent(?) solution of figuring out `--module-path`, please be my guest.

**Comment by cpovirk** [comment]
Oh, and in all this, I've been forgetting about the problem _linking to_ the JDK. I would guess (but haven't checked) that that problem is a result of the same commit as the other problem. It may be related to how we still [link (well, _try_ to link) to JDK 9](https://github.com/google/guava/blob/24b086da446d8f8010ee8e46c585f4e617049c16/guava/pom.xml#L174-L191), which of course supports the module system _but_ does not yet include the module name in the path of the Javadoc it produces.

**Comment by cpovirk** [comment]
It looks like https://github.com/google/guava/pull/7087 fixes _linking_ in _snapshot_ Javadoc by switching to Java 21 for snapshot-Javadoc generation.

If we want to make things work for our _releases_, then we can do that by using Java 21 for our releases, too. (Now, I've always been in the habit of using _snapshot_ Javadoc, myself. But I don't know what most users do.)

If we switch to Java 21, we'll have to be careful to continue to generate bytecode that works under older versions (which `-target` doesn't guarantee). Fortunately, Animal Sniffer _usually_ accomplishes that, such as with [a recent problem with `SequencedCollection` in Java 21+](https://groups.google.com/g/guava-discuss/c/IXWZCHn7yJs/m/7zptHzJHAAAJ). (See also https://github.com/google/guava/issues/6903 and https://github.com/google/guava/pull/6832.) That's more important for releases than for snapshots, but we would of course prefer not to break snapshots under older JDKs, either :)

**Comment by cpovirk** [comment]
(Snapshot docs are built by a different workflow task/whatever than snapshots themselves, so we could also use Java 21 for one but not the other. _Releases_ currently use the same Java version for each.)

**Comment by cpovirk** [comment]
Wait, no, #7087 (aka #7102 aka https://github.com/google/guava/commit/f2b8c4f47f253bb83c7959ffd2b7346e473c2788) causes Javadoc generation to [fail](https://github.com/google/guava/actions/runs/8268463900/job/22622277231)?

```
Error: Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/javadoc/Doclet
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.loadDocletClass(Start.java:800)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.preprocess(Start.java:771)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:376)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:347)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:57)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:46)
Caused by: java.lang.ClassNotFoundException: com.sun.javadoc.Doclet
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 16 more
```

I had tested _something_ locally, but I guess it wasn't that. For now, I'll roll back to JDK 11.

**Comment by cpovirk** [comment]
I tried using the Java 21 version of Javadoc again after https://github.com/google/guava/pull/7516, and it looks like that still works OK (but presumably also still fails if we use it for JDiff). But I do see an error from Javadoc itself if I go all the way to Java _23_, mirroring our approach of running the newest _javac_:

```
[ERROR] error: Unexpected redirection for URL https://docs.oracle.com/javase/21/docs/api/element-list to https://docs.oracle.com/en/java/javase/21/docs/api/index.html
```

Changing our configuration to _link_ to Java 23 doesn't help:

```
[ERROR] error: Unexpected redirection for URL https://docs.oracle.com/javase/23/docs/api/element-list to https://docs.oracle.com/en/java/javase/23/docs/api/index.html
```

So we probably wouldn't go past Java 21 for Javadoc yet.

(There are also some warnings, which might already arise with Java 11's Javadoc but which (if so) are hidden by repeated warnings: "[WARNING] javadoc: warning - The code being documented uses packages in the unnamed module, but the packages defined in https://docs.oracle.com/en/java/javase/21/docs/api/ are in named modules.")

**Comment by cpovirk** [comment]
The inability to inherit also leads to these warnings (if we dial up Javadoc warnings enough):

```
guava/src/com/google/common/util/concurrent/AbstractFuture.java:433: warning: overridden methods do not document exception type java.util.concurrent.CancellationException (package java.util.concurrent class CancellationException)
   * @throws CancellationException {@inheritDoc}
     ^
guava/src/com/google/common/util/concurrent/AbstractFuture.java:547: warning: overridden methods do not document exception type java.util.concurrent.CancellationException (package java.util.concurrent class CancellationException)
   * @throws CancellationException {@inheritDoc}
     ^
```

I have wondering if we could avoid that by omitting the `@throws` clauses entirely, but it turns out that we can't: I confirmed with a self-contained project that _unchecked_ exceptions appear in the subclass Javadoc only if we use `@throws` there.

**Comment by cpovirk** [comment]
The inheriting part still isn't fixed; GitHub just over-matched on the commit description.

**Comment by cowwoc** [comment]
@cpovirk Should I open a separate issue for the fact that we still can't link to Guava's Javadoc from other projects? Or does this issue cover that use-case as well? If my project links to Guava I get:

> [WARNING] warning: The code being documented uses modules but the packages defined in https://guava.dev/releases/33.5.0-jre/api/docs/ are in the unnamed module.

This leaves me with the undesireable choice of either removing `<failOnWarnings>true</failOnWarnings>` or removing links to Guava. I opted for the latter because otherwise I keep on missing Javadoc build problems.

**Comment by cpovirk** [comment]
Oh, right, that :( I know that you've commented on [#5653](https://github.com/google/guava/issues/5653)—does that seem suitable? I still probably won't try to understand it soon, sadly.

**Comment by cowwoc** [comment]
Good point. Let's stick with #5653. Thanks.
