### ISSUE TITLE
InternetDomainName.topPrivateDomain() throws exception for Amazoaws-Domain

### ISSUE THREAD

**Issue by kindlerm1958** [google/guava#7151]
### Description

We just noticed that the method InternetDomainName.topPrivateDomain() throws an IllegalStateException for the host s3-eu-west-1.amazonaws.com. Strange: replacing the "s3" by something else works as expected.

### Example

```java
import com.google.common.net.InternetDomainName; 

public class GuavaTest {

	public static void main(String[] args) {
		final String host = "s3-eu-west-1.amazonaws.com"; //s4-eu-west-1.amazonaws.com works
		
		InternetDomainName domainName = InternetDomainName.from(host);
		if (domainName.hasPublicSuffix()) {
			System.out.println(host + " hasPublicSuffix");
            System.out.println("topPrivateDomain: " + domainName.topPrivateDomain().toString());
        }

	}

}
```

### Expected Behavior

s3-eu-west-1.amazonaws.com hasPublicSuffix
topPrivateDomain: amazonaws.com

### Actual Behavior

s3-eu-west-1.amazonaws.com hasPublicSuffix
Exception in thread "main" java.lang.IllegalStateException: Not under a public suffix: s3-eu-west-1.amazonaws.com
	at com.google.common.base.Preconditions.checkState(Preconditions.java:604)
	at com.google.common.net.InternetDomainName.topPrivateDomain(InternetDomainName.java:466)
	at de.swr.online.GuavaTest.main(GuavaTest.java:13)

### Platforms

Java 8, Java 11, Java 17

### Checklist

- [X] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

**Comment by cpovirk** [comment]
s3-eu-west-1.amazonaws.com [is itself a public suffix](https://github.com/publicsuffix/list/blob/53b3d994c7f35260ef5583fb8bd9271aea07f7ab/public_suffix_list.dat#L11686), so it does not have a private domain.

**Comment by kindlerm1958** [comment]
I see.
So it is not safe to do the following (as we currently do):
if (domainName.hasPublicSuffix()) {
                return domainName.topPrivateDomain().toString();
            }
?
We will have to check wheter domainName IS a pubic suffix not just whether it has one?

**Comment by cpovirk** [comment]
If you want to know whether `topPrivateDomain()` is safe to call, then the method to call is `isUnderPublicSuffix()`, rather than `hasPublicSuffix()`.

**Comment by kindlerm1958** [comment]
Thanks a lot! Now it works as expected
